### ISSUE TITLE
Support for tslint

### ISSUE THREAD

**Issue by johnwiseheart** [CompuIves/codesandbox-client#1073]
# 🌈 Support for TSLint linting

Currently CodeSandbox has support for eslint, and it has support for Typescript. I feel like a solid next step in the linting game is support for [tslint](https://github.com/palantir/tslint), the TypeScript linter.

I would expect that if a user has a tslint.json file in their repo, that their code will be run through tslint.

I made [this](https://palantir.github.io/tslint-playground/) ([github](https://github.com/palantir/tslint-playground)) initially to prove that tslint could be run in-browser. The only downside to this setup seems to be that users can't use custom tslint rules, since that would require pulling each of the packages containing custom rules.

I was considering implementing that, but I feel like CodeSandbox is potentially a better place for this to live given how fully featured it already is.

Thoughts here? I'd definitely be open to helping to contribute to this, but I don't have a solid idea of where to start, or whether its something that you agree we should add.

**Comment by SaraVieira** [comment]
Hey!

TSLint is going to be deprecated as eslint now supports typescript and we do support eslint.

I will close this issue as implementing tslint now would not make sense

**Comment by kyr0** [comment]
<img width="1119" alt="Bildschirmfoto 2019-05-29 um 00 17 00" src="https://user-images.githubusercontent.com/454817/58516101-2e6e1a80-81a7-11e9-8035-af9b81bb6fd1.png">

eslint has a parsing error with visibility like "protected", also for `export default enum Abc { }` cases.
How to fix that?

I'm currently unable to use codesandbox because my valid code doesn't compile :)
