### ISSUE TITLE
When disable Vim mode the code disappears

### ISSUE THREAD

**Issue by radi-cho** [CompuIves/codesandbox-client#118]
Hello! When I click `preferences` and select `Vim mode` everything is great, **but when open `preferences` again and disable the Vim mode**, the code _**disappears**_... View:

![image](https://user-images.githubusercontent.com/12954909/29381446-e5783d5e-82d1-11e7-8d2a-6df3e47c7abd.png)

Video: https://youtu.be/KOo8K0i_Uog
I'm using Windows 10 x64bit, Chrome 60

**Comment by johann-sonntagbauer** [comment]
After a quick look it seems that there are two problems here:

1. code mirror keeps some references on the dom nodes
solution would be to call setValue('') to clean up the internal document of the editor during unmount

2. eslint throws because it tries to load babel-polyfill, which only alows one instance to be loaded at the same time. 

All in all it seems that there is a migration path from code mirror towards monaco. So following options are possible
1. fix the bugs 
2. try to get vim support going in monaco editor https://github.com/VSCodeVim/Vim

**Comment by CompuIves** [comment]
Ah, I see. Didn't know that codemirror kept its references, but makes sense.

Getting VIM support in Monaco is high priority, because it's the only thing keeping us from dropping codemirror support, now we have to support both. Just created an issue for it: https://github.com/CompuIves/codesandbox-client/issues/125.

If the bugs aren't hard to fix, then we can still fix them. I reckon it is just a matter of deleting the div from codemirror to make it lose its references so Monaco can use it.

**Comment by johann-sonntagbauer** [comment]
@CompuIves the code mirror problem is easy to fix. 

Much bigger trouble is the second one with es-lint.
There I don't know for now how to fix that because babel-polyfill is part of both es-lint plugins. 
Maybe loading babel-polyfill beforhand can solve that, but don't know exactly if that will help.

**Comment by CompuIves** [comment]
Hmm, yes. There are two linting modules. One in a web worker, used by Monaco, and one in a simple module (so on the window).

I think it would be smart to move the simple module to the web worker as well and make the web worker a singleton that can be used both Monaco and CodeMirror.

On a related note, I also put some thought in how to get `babel-eslint` working in ESLint. For that to happen we need this change: https://github.com/eslint/eslint/pull/9119. But we can run on a custom build before that PR is merged. 

I'm thinking that we could combine both efforts, move eslint to a singleton + use a custom build that's using the babel parser.

**Comment by johann-sonntagbauer** [comment]
Looks promising. I have to analyse further but it seems reasonable.
