### ISSUE TITLE
No Type Checking on initial load

### ISSUE THREAD

**Issue by eps1lon** [CompuIves/codesandbox-client#1217]
# 🐛 bug report

## Description of the problem
No type errors are reported in the editor or console.
## How has this issue affected you? What are you trying to accomplish?
On the initial load of https://codesandbox.io/s/react-ts I get type errors as well as #1205. Once I fork this I don't get type errors or the linked issue.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | `PROD-1540023398-4e289bd`
| Browser | Version 70.0.3538.67 (Official Build) (64-bit)
| Operating System | Ubuntu 16.04.5 LTS

**Comment by eps1lon** [comment]
I'm currently encountering one of the following states though I cant reproduce them deterministically:
- no typechecking (with type information in the editor though)
- typechecking and #1205

**Comment by CompuIves** [comment]
Yes, I think this is an issue for all TS projects right now. When you just load a sandbox there are no type errors, because the typing files haven't been downloaded yet. Only when you switch a file we start type checking.

We should fix this!

**Comment by eps1lon** [comment]
@CompuIves They should probably treated as normal dependencies when listed as such.

Some more observations:
- I don't have to change a file. Simply editing triggers typechecking
- experimental vscode editor does not trigger #1205

**Comment by CompuIves** [comment]
> They should probably treated as normal dependencies when listed as such.

Agreed, but we only start downloading dependency files after the editor has been loaded, otherwise we would have a pretty big startup time. I need to find a way to trigger a type check in Monaco/VSCode after the files have been downloaded, that should be enough to make it work.

> experimental vscode editor does not trigger #1205

This is interesting, I tested with the experimental editor (I use this as my primary editor) and it seemed to work. Does clearing the cache work?

**Comment by eps1lon** [comment]
Tested again (incognito window, disabled cache, disabled service worker) and now I encounter #1205 in the normal and experimental editor once typechecking kicks in.

**Comment by CompuIves** [comment]
Hmm, so you see the red squiggles for all files?

**Comment by eps1lon** [comment]
I switched to https://codesandbox.io/s/j4wkmo2nx3 but the original sandbox with `react-scripts-ts` has the same issue. A [fork of react-ts](https://codesandbox.io/s/kwz6q3rw87) however has no typechecking at all.

I'm trying a local dev setup to verify that this is not some weird issue with caching or serviceWorkers.

**Comment by CompuIves** [comment]
Oh yep! I'm having the same issue now, it happens when adding @material-ui/core. This is a problem on our side, we cancel download type files for dependencies that have more than 400 typing files to download (otherwise the editor would get laggy and lots of download).

It seems that react/react-dom typings are also cancelled by this for some reason, which is really weird.

I wish we wouldn't have to eagerly download type files, but as it is now the typescript language server requires us to resolve typing files synchronously, that's why we download them eagerly. I'll see what I can do to optimize this and let the typings of @material-ui/core not affect those of react/react-dom.

**Comment by CompuIves** [comment]
This perfectly describes the issue: https://github.com/Microsoft/TypeScript/issues/1857#issuecomment-289123408

**Comment by eps1lon** [comment]
With a local setup on master I get no typechecking in the normal editor. The experimental editor works perfect.

I would like to bundle our typings into a single file but all the packages I know don't support bundling for declaration files. I guess this can become an issue for other libraries since typescript emits declarations for every file and 400 is not that many but I totally get why you bail out.

So once Microsoft/TypeScript#4433 is resolved this won't be an issue.

But thanks for your help. Really appreciated!

**Comment by CompuIves** [comment]
I found a compromise where you won't be able to open the type definitions in the editor, but they will be available in the type checking! Will go live today.
