### ISSUE TITLE
Emmet auto-markup in JS in non html files

### ISSUE THREAD

**Issue by Sharpie360** [CompuIves/codesandbox-client#1230]
# 🐛 bug report

### Vanilla Sandbox
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | Vue.js && Parcel
| Chrome  | Version 69.0.3497 |
| Operating System | Windows 10 |

**Comment by CompuIves** [comment]
Ahh, I see the issue here. We enabled it for React/Preact projects, but I can see that it can be irritating.

Does it automatically apply the autocompletion for you? I tested a bit in VSCode and noticed the same behaviour, but I can see that it's very irritating if it accidentally applies the transformation.

![image](https://user-images.githubusercontent.com/587016/47498397-70c02980-d85d-11e8-89be-303ef4b6c920.png)

**Comment by Sharpie360** [comment]
It does seem to happen pretty regularly, although im not using any react or preact libraries, is that a feature that could be set based on if the file is a react file or not? maybe check if nothing in the package.json refers to anything react, then emmet could auto default to disabled for js files?

**Comment by smdimagerie** [comment]
Could it be a Toggle option, like the Use CodeMirror ?

**Comment by CompuIves** [comment]
> maybe check if nothing in the package.json refers to anything react, then emmet could auto default to disabled for js files?

I initially wanted to implement this, but then I realized that lots of dependencies we don't know about could be using JSX.

I think we should make this a setting, so I will work on that somewhere this week!

**Comment by Sharpie360** [comment]
That's a very good point! I think a toggle option would be the best solution.

**Comment by Sharpie360** [comment]
Emmet seems to be working correctly now from my experience. 😄
