### ISSUE TITLE
Fix custom font families in Monaco

### ISSUE THREAD

**Issue by CompuIves** [CompuIves/codesandbox-client#126]
I had to disable the custom font family feature in Monaco due to a problem with Windows recalculating the widths of the characters. This feature is very important though and it would be nice to get it working again. I don't have a Windows PC, so this makes it hard for me to fix this.

This is the commented out code:
https://github.com/CompuIves/codesandbox-client/blob/master/src/app/components/sandbox/CodeEditor/Monaco.js#L745

**Comment by radi-cho** [comment]
I'm from the phone now

**Comment by radi-cho** [comment]
I want to enable the custom font family feature but i don't have write permissions. Can you enable it?

**Comment by radi-cho** [comment]
View this - https://github.com/CompuIves/codesandbox-client/pull/136
Please merge #136 to test the bug

**Comment by radi-cho** [comment]
### Update: I'll test this locally

**Comment by ndelangen** [comment]
I'm able to set a custom font for the editor, what is this issue exactly about? this code is commented out: https://github.com/CompuIves/codesandbox-client/blob/master/src/app/components/sandbox/CodeEditor/Monaco.js#L762

But I can set custom font here:
<img width="1788" alt="screen shot 2017-08-25 at 13 14 05" src="https://user-images.githubusercontent.com/3070389/29711884-5ec473d2-8997-11e7-93af-98a420e5303a.png">

So my question is, since this is tagged "beginner friendly" I'm not sure what needs to be done?

**Comment by radi-cho** [comment]
@ndelangen This issue is for Monaco editor. You're using CodeMirror (I saw on the screenshot)
And the code is commented because there is another bug

**Comment by donysukardi** [comment]
@CompuIves perhaps we should add a setting to enable it regardless (with some warning message). We shouldn't punish macOS users :grin:

**Comment by CompuIves** [comment]
You're right @donysukardi. We could detect if the browser is Windows and hide the preference for them in the meantime. Would you be interested in opening a PR for this?

**Comment by donysukardi** [comment]
@CompuIves I uncommented your code and tested it on Windows VM, both on Chrome and Edge. It seems that it's only not getting it the first time round. When I adjust the font size, the display would then be correct.

After that if I reload the browser, the display is fine. It's still usable after all.
Here's the screenshot of it running on Edge, with my patched version of Operator Mono and ligatures enabled.

![image](https://user-images.githubusercontent.com/410792/32280014-6d4dc130-bf55-11e7-9408-bdcdacfd3bdd.png)

Perhaps we could enable the feature and add "Experimental, page refresh might be required" note.

I'll try to further investigate. Re-rendering the entire MonacoEditor might help :)

**Comment by CompuIves** [comment]
Hmm, interesting. Before this it persisted between refreshes. What happens when you change the line height?

**Comment by donysukardi** [comment]
I made two very interesting observations. These happen on Windows Chrome.

1. When I type in the line height field, for the first value(e.g. 1.5) the editor's line height resets to 1 and then when I enter another value (e.g. 1.7), it uses the previous one (which is 1.5).
 
![typing](https://user-images.githubusercontent.com/410792/32280562-46e20cde-bf57-11e7-8522-2cd90ad464e2.gif)

2. It seems to be working fine if I toggle it via the input spinner

![spinner](https://user-images.githubusercontent.com/410792/32280565-49c7270e-bf57-11e7-817a-75dd5720cbee.gif)

Might have to do with how the event is handled.
Anyway, I just tested again, refreshing the page does give the desired font family, font size, and line height.

**Comment by donysukardi** [comment]
Okay, apparently the same issue as issue 1 above happens when I just change the font size on Mac Chrome by typing into the field.

![image](https://user-images.githubusercontent.com/410792/32282983-154f8424-bf5e-11e7-94ae-b8d11082ceb4.png)

It might not have to do with Monaco after all. I'll try delving into the code :)

**Comment by CompuIves** [comment]
It's back when I disable ligatures on Windows (tracking #729)
