### ISSUE TITLE
How add a global module ? 

### ISSUE THREAD

**Issue by Guihgo** [CompuIves/codesandbox-client#1267]
# ❔ Question

Is there any way to add global package to use on terminal ? 

I want install AtomicReact module globally to use CLI commands.

**Comment by lbogdan** [comment]
Hey @Guihgo ! You can install the package locally, and then run `yarn cli_command` or `npx cli_command`.

**Comment by fweth** [comment]
What if a script assumes some variable to be in $path?  I try to run PureScript, where this seems to be the case (`[error] Executable was not found in path: "purs"`).

**Comment by lbogdan** [comment]
@fweth Where is that `purs` located?

**Comment by fweth** [comment]
@lbogdan I don't know the specifics, I just tried to follow the [this guide](https://github.com/purescript/documentation/blob/master/guides/Getting-Started.md).  After installing `purescript` and `spago`, I try to do e.g. `spago repl`, it doesn't work because `spago` is not in the path, if I explicitly evoke `~/.bin/yarn/spago repl` I get the error `Executable was not found in path: "purs"`.

**Comment by eagle-k** [comment]
By installing both PureScript and Spago locally, I was able to run PureScript code on the container.
However, since the VSCode extension of the PureScript IDE is not supported, I found it impractical to develop on Codesandbox.
