### ISSUE TITLE
Files on ./sandbox folder doesn't showed on FileEditor

### ISSUE THREAD

**Issue by Guihgo** [CompuIves/codesandbox-client#1270]
# ❔ Question

Files on ./sandbox folder doesn't showed on FileEditor.
When i type `ls` command on terminal there are a lot of files doesn't showed on FileEditor, how can i show them ? 

###  Link to sandbox: [link](https://codesandbox.io/s/v3no221955)

**Comment by CompuIves** [comment]
Hey! This is currently a feature we're missing, but we're deploying this
functionality within a few days. Stay tuned!

**Comment by Guihgo** [comment]
> tly a feature we're missing, but we're deploying this functionality within a few days. St

**Comment by resurge** [comment]
Hi, has this feature been deployed?
Because I seem to be having the exact same issue. 

If i run `touch testfile` in a terminal a new file is visible when i run `ls`.
But the file list in the top left doesn't show it.

A similar issue exists in the reverse order.
When creating a new file in the file view, it's visible in the terminal using `ls`.
But when creating a folder instead it is _not_ shown!

**Comment by lbogdan** [comment]
Hey @resurge ,

Yes, this has been deployed long ago, but there are some special cases in which it doesn't work as expected. Can you please provide the link to the sandbox, so I can take a look?

> But when creating a folder instead it is not shown!

That's because we treat folders kind of like git does, where you can't add empty folders. Not saying it's ideal UX 🙂, only acknowledging it's something we're aware of.

**Comment by resurge** [comment]
> Hey @resurge ,
> 
> Yes, this has been deployed long ago, but there are some special cases in which it doesn't work as expected. Can you please provide the link to the sandbox, so I can take a look?
> 
> > But when creating a folder instead it is not shown!
> 
> That's because we treat folders kind of like git does, where you can't add empty folders. Not saying it's ideal UX slightly_smiling_face, only acknowledging it's something we're aware of.

Link to the sandbox: https://codesandbox.io/s/typescript-express-react-template-hf0zh

I've only just begun using the terminal on CodeSandbox since I wanted to try to create my own template.
My idea was to start from the regular node template, and then run create-react-app in the terminal to get the files that CRA creates.
And then to merge both package.json's and the files so that the template would both support ts-node for the backend and CRA for the frontend part.

**Comment by lbogdan** [comment]
Unfortunately this doesn't quite work, because of how syncing files between the container and the API / editor works, of which you can read more about [here](https://spectrum.chat/codesandbox/help/codesandbox-container-is-not-handling-package-changes-well~e42fa1e1-53b3-420f-9335-ae5e8a8422fa?m=MTU2ODM3NzkwNzAxNw==) (you have to scroll down a bit to see my comment).

My workflow for creating server templates is a bit different — I first get it working locally, then I add a `sandbox.config.json` to the project root with the following contents:
```json
{
  "template": "node"
}
```
and commit everything to a GitHub repo. I can then just import that into CodeSandbox by going to (for example) https://codesandbox.io/s/github/lbogdan/csb-vue-vite (which imports this GitHub repo: https://github.com/lbogdan/csb-vue-vite ).

**Comment by resurge** [comment]
> My workflow for creating server templates is a bit different — I first get it working locally, then I add a `sandbox.config.json` to the project root with the following contents:

I had a suspicion I might need to do it like this.

Also, I was on [this](https://codesandbox.io/docs/environment#container-environment) page multiple times yet I completely overlooked the explanation on the bottom about this behaviour! 🤦‍♂️
My apologies for not reading more closely.

And thank you for the explanation on the inner workings and the fast responses.
