### ISSUE TITLE
Loading Sandbox Fetching gitrepository .. forever

### ISSUE THREAD

**Issue by RichardJJacobs** [CompuIves/codesandbox-client#1294]
# 🐛 bug report

## Description of the problem
When I try and access my angular sandbox I just get "Loading Sandbox Fetching gitrepository" which just sits there forever. Reloading doesn't help. I'm not even using git as a repository. I created the sandbox by running codesandbox ./ in the project directory. It also seems very very slow loading files. Is this because its trying to test the software on the fly? Is there a way of turning this off while I upload the files. Can't find anything in the docs.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | Chrome
| Operating System |W10

**Comment by Pathel** [comment]
Seeing this same issue with my sandbox: https://codesandbox.io/s/wnn8kkzkl5

**Comment by RichardJJacobs** [comment]
There seems to be no support for codesandbox. I posted to this thread and also emailed the developers but no response. I'm looking around for a better sandbox.

**Comment by lbogdan** [comment]
@Pathel We had some DDoS issues earlier, your sandbox seems to work fine now, can you confirm?

@RichardJJacobs Sorry for the radio silence, since you didn't follow up, we thought that you had a spurious issue that resolved by itself. Are you still having issues? If yes, a link to your sandbox would greately help.

**Comment by RichardJJacobs** [comment]
What do you mean by follow up? Do issues have to be reported more than once?

**Comment by RichardJJacobs** [comment]
https://codesandbox.io/s/x2375zo7vw
I got the original issue fixed by posting on stackoverflow - it was due to an angular.json problem, although the angular.json seemed ok in visualstudiocode. Following that fix I then got hundreds of errors so gave up as I hadn't had a response to the first issue.

**Comment by lbogdan** [comment]
Yeah, Angular is quite the beast, and, although we tried to keep up to date with the latest version(s), it still breaks once in a while. However, since we launched [CodeSandbox Containers](https://hackernoon.com/codesandbox-containers-5864a8f26715), there's also the possibility of running your Angular project in a container and edit it and preview inside CodeSandbox - this is your sandbox running in a container: https://codesandbox.io/s/mj1z0o2wz9 (the only changes were adding the `sandbox.config.json` and adding `import "zone.js/dist/zone";` to `pollyfills.ts`, as it was complaining that "In this configuration Angular requires Zone.js").

**Comment by RichardJJacobs** [comment]
Ok thanks. How do I get a project to run in a container? The way I loaded my first project was by running codesandbox ./ in my project directory.

**Comment by lbogdan** [comment]
You need a `sandbox.config.json` in the project folder, with
```json
{
  "template": "node"
}
```
(or a different server template, if you're using a framework we support, you can see the list [here](https://codesandbox.io/s/), under "Server Templates").

Worth mentioning that it only works with sandboxes imported from github or from codesandbox-cli, currently there is no way to easily change a client sandbox to a server one.

**Comment by RichardJJacobs** [comment]
That works. Thanks.

**Comment by lbogdan** [comment]
Nice, I'm gonna close this, then. If you have further issues, you can find me on [CodeSandbox Discord](https://discord.gg/KE3TbEZ), I'm @BogdanL there.
