### ISSUE TITLE
Math.random() does not generate random numbers

### ISSUE THREAD

**Issue by zkwsk** [CompuIves/codesandbox-client#1310]
# 🐛 bug report

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |
| Chrome | 70.0.3538.102 |
| Mac OS X | 10.13.6 |

Screenshot:
<img width="1122" alt="screenshot 2018-11-18 11 03 16" src="https://user-images.githubusercontent.com/1968912/48670986-cb2d6c80-eb21-11e8-9e26-4199dc213dcf.png">

**Comment by CompuIves** [comment]
Hmm, I think this is expected behaviour. When you evaluate `randomValue()` you get a random value back, the array then gets prefilled with this value (https://github.com/spion/array-2d.js/blob/master/array-2d.js#L4-L12). If you'd execute this locally I think you'd see the same result.

I'll keep this open so you can double check, maybe I'm wrong.

**Comment by zkwsk** [comment]
You're right. Happens locally as well. Did not consider that the Array2D constructor might not be designed to accept a function. Sorry for bothering :)
