### ISSUE TITLE
Can't invalidate cached dependencies

### ISSUE THREAD

**Issue by Andarist** [CompuIves/codesandbox-client#1355]
# 🐛 bug report

## Description of the problem

We had a bug report with repro on codesandbox, the bug got fixed and I have wanted to confirm that it has been fixed by updating the codesandbox dependencies, but I cant make it work (even when I copy-paste sandbox code into a completely fresh sandbox). It still uses old version of `pose-core`.

###  Link to sandbox:
Forked & updated  with pose-core@2.0.2 added as dep (its transitive dep of react-pose, I've tried to trigger new version of pose-core with it) https://codesandbox.io/s/ll0nq24l9
Fresh sandbox with `react-pose` dep which should install fresh pose-core@2.0.2 - https://codesandbox.io/s/jzx1zw2jx3

**Comment by lbogdan** [comment]
Can confirm, the root issue seems to be that the packager returns `pose-core@2.0.2` for https://d1jyvh0kxilfa7.cloudfront.net/v1/combinations/babel-runtime@7.3.1%2Bcsbbust@1.0.0%2Bpose-core@2.0.2%2Breact@16.6.3%2Breact-dom@16.6.3%2Breact-pose@4.0.3.json :
```json
{
  [...]
  "/node_modules/pose-core/package.json": {
    "content": "{\"name\":\"pose-core\",\"version\":\"2.0.0\", [...]
  }
}
```

Doesn't look like a cache issue, though, because bumping `react` and `react-dom` to `16.7.0` doesn't seem to change anything: https://d1jyvh0kxilfa7.cloudfront.net/v1/combinations/babel-runtime@7.3.1%2Bcsbbust@1.0.0%2Bpose-core@2.0.2%2Breact@16.7.0%2Breact-dom@16.7.0%2Breact-pose@4.0.3.json .

**Comment by CompuIves** [comment]
Fixed this one with the new packager, hopefully live this week!
