### ISSUE TITLE
Error importing dependency express-graphql

### ISSUE THREAD

**Issue by aadamsx** [CompuIves/codesandbox-client#1397]
I'm using the Node sandbox template... 

```json
\\package.json
  "dependencies": {
    "apollo-datasource-rest": "latest",
    "apollo-server": "2.1.0",
    "body-parser": "1.18.3",
    "express": "4.16.4",
    "express-graphql": "0.7.1",
    "graphql": "14.0.2"
  },

```

When adding express-graphql I get the following message.

[nodemon] starting `node index.js localhost 4000`
module.js:550
    throw err;
    ^

Error: Cannot find module 'express-graphql'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/sandbox/index.js:4:21)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

**Comment by lbogdan** [comment]
Hey @aadamsx , can you give us the url to that sandbox?

**Comment by aadamsx** [comment]
Sure, here you go: https://codesandbox.io/s/0xjv1pmnxv

I tried both the Node and Apollo templates.  Just adding ```const graphqlHttp = require("express-graphql");``` is enough for any of these templates to throw.

**Comment by aadamsx** [comment]
I just signed up as a patron yesterday since the service is so useful. :)

**Comment by lbogdan** [comment]
Ok, you're getting that error because `yarn install` errors because of
```
[2/4] Fetching packages...
error https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"
```

This is caused because NPM removed event-stream version 3.3.6 from
their registry (you can read more about it here:
https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident),
but you have a reference to it in your yarn.lock, because `nodemon` (indirectly) depended on it (to see which package(s) depend on a package, you can run `yarn why package-name`).

You can solve this by opening a terminal into your sandbox (expand the button "Terminal" and click on the plus icon) and doing `yarn upgrade nodemon`. I did that on a fork of your sandbox, you can check the result is here: https://codesandbox.io/s/m3wp7o7pmp .

**Comment by aadamsx** [comment]
That worked great!  Thanks for the help!  I didn't realize I could terminal in an update the dependencies like this... this is just like a local enviornment, which is awesome!  

Very happy to pay for this service!

**Comment by lbogdan** [comment]
Glad you're enjoying it!

> this is just like a local enviornment, which is awesome!

That was the whole idea with [CodeSandbox Containers](https://hackernoon.com/codesandbox-containers-5864a8f26715), to have a complete development environment, only in the cloud! 🙂 

I'm gonna close this, if you need further assistance please open a new issue, or, if it's more like questions / suggestions, you can also join us on [Spectrum](https://spectrum.chat/codesandbox)!
