### ISSUE TITLE
Switching "Use CodeMirror" twice causes empty files.

### ISSUE THREAD

**Issue by renegoretzka** [CompuIves/codesandbox-client#142]
Switching "Use CodeMirror" twice causes empty files when Option is deactivated
See short video here: https://cl.ly/3L1V0j0s0v13

I use Safari 10.1.2 on MacOS Sierra.

I also found that the option switch is not switching when clicking after first time.

**Comment by Arthelon** [comment]
I don't see this issue in the HEAD of the current development branch. Should be fixed with the next update!

**Comment by CompuIves** [comment]
Hmm, yes, I remember this being fixed by this https://github.com/CompuIves/codesandbox-client/pull/129 PR. But it seems like I get the error again in production when switching:

![screen shot 2017-08-23 at 17 10 22](https://user-images.githubusercontent.com/587016/29623234-fcc6fef6-8825-11e7-8b73-2964ac98408a.png)

Do you recognize this error @johann-sonntagbauer? Maybe I did something that broke the fix again.

**Comment by johann-sonntagbauer** [comment]
I am on it already :). 
The "fix" of mine is more a hack to circumvent the eslint module loading quirks. Hope that Monaco will become the default editor in the near future to save us from these headaches.

**Comment by CompuIves** [comment]
I really hope so too. Only thing holding me back is https://github.com/CompuIves/codesandbox-client/issues/125, we have a lot of VIM users.

**Comment by lbogdan** [comment]
Related (or maybe not?) when switching from Monaco to CodeMirror (actually when initializing CodeMirror) I get this `Warning: Unknown props `isLoading`, `pastDelay`, `error` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Loadable)`.
