### ISSUE TITLE
GitHub import not working: CSB is not shown in my Dashboard

### ISSUE THREAD

**Issue by nikolasburk** [CompuIves/codesandbox-client#1433]
# 🐛 bug report

## Description of the problem

I'm trying to import [this](https://github.com/prisma-csb/graphql-example-js) GitHub repo. But there are two issues:

- After having imported it with the import wizard, I _can_ see the CSB with the proper file structure under this URL: `https://codesandbox.io/s/github/prisma-csb/graphql-example-js`. However it does not seem to be stored in my CSB account. It's not in the dashboard nor can I find it anywhere else. I was also surprised that I can actually make changes to the imported files, in the docs it says that imported CSBs are immutable?!
- It immediately throws the error `Class extends value undefined is not a constructor or null` when executed in the CSB

To check that the code for the CSB works, you can test the app from the repo yourself:

```
git clone https://github.com/prisma-csb/graphql-example-js
cd graphql-example-js
yarn install
yarn start
```

###  Link to sandbox: [link](https://codesandbox.io/s/github/prisma-csb/graphql-example-js)

**Comment by lbogdan** [comment]
Hey @nikolasburk ,
1. Yes, sandboxes imported from github are not owned by anyone (or you could think about them as being *owned by github*, because they keep in sync with the github repo they were imported from, updating whenever you push new commits etc.). If you want to own it and be able to edit it, you'll have to fork it.
2. `graphql-yoga` (or any other graphql server, for that matter - and maybe `prisma`, too?) is not supported in client sandboxes (because it uses node APIs); to make it work you need to use a [server sandbox](https://hackernoon.com/codesandbox-containers-5864a8f26715), and in order to do that you'll have to add a `sandbox.config.json` file in your repo root, with the following contents:
```json
{
  "template": "node"
}
```

Let us know if you have difficulties in making it work.

**Comment by nikolasburk** [comment]
Hey @lbogdan, thanks so much for your quick response. Your explanations make a lot of sense, would it maybe be possible to omit the `sandbox.config.json` file and instead use a query argument for the Sandbox URL?

**Comment by lbogdan** [comment]
Not really, that's needed by the [github importer](https://github.com/codesandbox/codesandbox-importers/), which is a separate service.
