### ISSUE TITLE
Add Paste to Command Palette

### ISSUE THREAD

**Issue by zixuan75** [CompuIves/codesandbox-client#1481]
# 🌈 Feature

I've been annoyed when CodeSandbox has no Paste button and it's not in the Command Palette. I think that the Paste button should be when I right click anywhere in the code and it should appear saying "Paste" and it's on the bottom of the menu bar that appears.

When I right click on code it should appear the "Paste" button, to paste the thing I've cut or copied.

Let's say I want to separate the properties from the main file and move it to some other JS file that I've created for it, I would right click and hit "Cut" on the main file and then change the current file to the properties file, then right click and hit "Paste" on the properties file.

**Comment by PAEz** [comment]
This isn't a problem with codesandbox but rather the editor used and the fact that paste is considered a security risk.  Codesandbox uses [Moanco](https://microsoft.github.io/monaco-editor/) which creates its own context menu and doesnt use the browsers standard one.  So it has to recreate the paste option but its to lazy to do it its self and relies on document.execCommand('paste') which is banned due to security reasons.  Heres an [issue](https://github.com/Microsoft/monaco-editor/issues/391) for Monaco outlining the problem.  
But all thats for normal people, we're nerds we dont have to put up with that ;P  
Below is the source to a very simple FF addon that enables paste for codesandbox and would prolly work for other sites using Monaco.  Im to ~~lazy~~busy right now to do the icons, screenshot, blah, blah but if no one else wants to do it either Ill do something later for ff and chrome.    
  
manifest.json
```javascript
{
	"manifest_version": 2,
	"name": "Paste for CodeSandbox",
	"version": "1.0",
	"description": "What the title says.",
	"icons": {},
	"content_scripts": [
		{
			"matches": ["*://codesandbox.io/*"],
			"js": ["script.js"],
			"run_at": "document_start"
		}
	],
			"permissions": ["clipboardRead"]
}
```
  
script.js
```javascript
exec(function () {
	// hijack the query and report paste supported
	var copyQuery = document.queryCommandSupported;
	document.queryCommandSupported = function(arg) {
		if (arg != "paste") return copyQuery.apply(document, arguments);
		return true;
	};

	// hijack the exec for paste and make it message back here to paste
	var copyExec = document.execCommand;
	document.execCommand = function(arg) {
		if (arg != "paste") return copyExec.apply(document, arguments);
		window.postMessage(
			{
				command: "paste"
			},
			"*"
		);
	};
});

window.addEventListener("message", function(event) {
	if (
		event.source == window &&
		event.data &&
		event.data.command == "paste"
	) {
	document.execCommand("paste");
	}
});


function exec(fn) {
	var args = "";
	if (arguments.length > 1) {
		for (var i = 1, end = arguments.length - 2; i <= end; i++) {
			args +=
				typeof arguments[i] == "function"
					? arguments[i]
					: JSON.stringify(arguments[i]) + ", ";
		}
		args +=
			typeof arguments[i] == "function"
				? arguments[arguments.length - 1]
				: JSON.stringify(arguments[arguments.length - 1]);
	}
	var script = document.createElement("script");
	script.setAttribute("type", "application/javascript");
	script.textContent = "(" + fn + ")(" + args + ");";
	document.documentElement.appendChild(script); // run the script
	document.documentElement.removeChild(script); // clean up
}
```

**Comment by SaraVieira** [comment]
Issue closed as we dropped the monaco editor in the latest release

**Comment by giorgi-m** [comment]
it seems I can't paste in code sandbox....

**Comment by Dmytro2V** [comment]
After 4 years still no 'paste' on right click menu :-0
