### ISSUE TITLE
Imported Parcel project behaves differently on local vs on codesandbox

### ISSUE THREAD

**Issue by hydrosquall** [CompuIves/codesandbox-client#1534]
# 🐛 bug report

## Description of the problem

Stylesheet isn't being applied in a parcel.js project in codesandbox that was imported from github, but it works locally and on other quick-app-deploy services, like Glitch.me

## How has this issue affected you? What are you trying to accomplish?

- I developed a `parcel.js` project that works when run locally or on `glitch.me`, but for some reason it seems that the stylesheet is not getting applied inside `codesandbox` and I can't figure out why.
- I'd like to be able to share the code samples in codesandbox because of all the great features + vscode integration, but if the app behaves differently than it does on local, we'll have to use other sharing tools instead (like Glitch).

###  Link to sandbox: 

- On Codesandbox [JS works, CSS is missing](https://codesandbox.io/s/zlxj9817km)
- On Glitch JS + Styles are applied correctly. [Demo](https://hydrosquall-graph-navigation-prototype-1.glitch.me/) / [Source](https://glitch.com/edit/#!/hydrosquall-graph-navigation-prototype-1)
- Source code of the repository being imported: https://github.com/hydrosquall/graph-navigation-prototype

### Your Environment

| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | Latest
| Browser | Chrome
| Operating System | Mac

**Comment by hydrosquall** [comment]
Seems like another user noticed a similar difference with parcel acting differently, but that issue was unresolved: https://github.com/CompuIves/codesandbox-client/issues/857

**Comment by CompuIves** [comment]
Hey @hydrosquall. Yep, this seems to be an issue with our in-browser bundler. It seems to have trouble to import the `sass` dependency.

The root cause of this issue is that we execute the sandbox in the browser, we simulate the behaviour of Parcel as a bundler. It seems that for the sandbox you mentioned we didn't detect that the sandbox was a parcel sandbox (we only check for `parcel-bundler`, I didn't know that `parcel` exists), so the template was `create-react-app` and the bundler settings were wrong. I have a fixed sandbox with `Vanilla` here: https://codesandbox.io/s/yq08vq3mn1.

At the same time, we also have a mode where we actually execute the sandbox on the server (this is the same behaviour as Glitch). To make that work you need to set the template to `"node"`, which I did in this PR: https://github.com/hydrosquall/graph-navigation-prototype/pull/1. This creates this sandbox: https://codesandbox.io/s/48z44q08z9 which also works as expected (as it's literally parcel 😄).

Containers are fairly new, that's why the switch between browser and container sandboxes and templates in general is not really clear yet. We are fixing this currently and hope to release that patch this month.

**Comment by hydrosquall** [comment]
Hey @CompuIves , that was so fast and thorough!!

Thank you so much. I also didn't realize I had the wrong `parcel` installed. Thank you for the PR and the explanation - I will happily migrate our project back to Codesandbox land :).

**Comment by hydrosquall** [comment]
parcel detection updated here: https://github.com/codesandbox/codesandbox-importers/commit/c469b20379045426a3dde36be69b21f54eae5390
