### ISSUE TITLE
VUE Inline SVG with vue-svg-loader

### ISSUE THREAD

**Issue by stefan0uh** [CompuIves/codesandbox-client#1557]
# ❔ Question

i tried to use `vue-svg-loader`, but i get always 
```
[Vue warn]: Invalid Component definition: <?xml version="1.0" encoding="UTF-8" standalone="no"?>
...
found in

---> <App> at /src/App.vue
       <Root>
```

and now i'm clueless, cause lokal it works on a new project with vue-cli

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1550701294-07ade81d
| Browser |  Google Chrome - Version 72.0.3626.109
| Operating System | Windows 10

**Comment by lbogdan** [comment]
Hey @stefan0uh ,

We don't currently (and probably never will) support `@vue/cli` 3 in browser sandboxes.

You can however use a [server sandbox](https://medium.com/@compuives/codesandbox-containers-out-of-beta-improvements-be79679df4cc) ; I took your sandbox and made an example here: https://codesandbox.io/s/github/lbogdan/vue-svg-loader-demo .

Lots of server sandboxes improvements are coming soon, a `@vue/cli` server template being one of them!

Closing this, as this is expected behavior.
