### ISSUE TITLE
React Modal no animation?

### ISSUE THREAD

**Issue by James2516** [CompuIves/codesandbox-client#156]
https://codesandbox.io/s/l5lj2x12kz

why isn't the modal animation showing on the code snippet above?

**Comment by CompuIves** [comment]
Hey @James2516, I just tested your sandbox locally and it also doesn't show any animation there. I can't help with debugging sandboxes if the bug is not related with CodeSandbox, for that I'd like to refer you to [Reactiflux](https://www.reactiflux.com/). Reactiflux is an amazing community that always is on standby if you need any help.
