### ISSUE TITLE
Ember Template Is Broken

### ISSUE THREAD

**Issue by jrock2004** [CompuIves/codesandbox-client#1560]
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?

Trying to create a new Ember sandbox, and ember is not compiling correctly

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | EmberJS Mike North
| Browser | Firefox
| Operating System | Mojave

![image](https://user-images.githubusercontent.com/655716/53185633-632d6d00-35cd-11e9-8b3f-5e3bf87c07ea.png)

**Update 1:** So it looks like I have to fork the initial project, then it will compile

**Comment by lbogdan** [comment]
The container was most probably out of sync with the sandbox, should be fixed with the [moving to the new container infrastructure](https://medium.com/@compuives/codesandbox-containers-out-of-beta-improvements-be79679df4cc), as we regenerated all the containers.

![image](https://user-images.githubusercontent.com/2083930/54831552-3602d600-4cc3-11e9-95dd-35694737a374.png)
