### ISSUE TITLE
super user password

### ISSUE THREAD

**Issue by iofirag** [CompuIves/codesandbox-client#1596]
# ❔ Question

Hi, just want to ask.

i have clone a [library](https://github.com/coolwanglu/pdf2htmlEX) in my sandbox,
by using `git clone https://github.com/coolwanglu/pdf2htmlEX` via the terminal.
i need to install it by `make` command (like wrote in their guide).

but i didnt have superuser password for the installation process.
how can i do that?

my sandbox (https://codesandbox.io/s/q80lzqym3j)
Chrome
windows 10

**Comment by lbogdan** [comment]
Hey @iofirag ,

I'm closing this, as we currently don't support this use case, and we don't provide root access, for obvious security reasons.

What you could do, though, is try to compile it inside the `/sandbox` folder, as you only need root access to copy the generated libraries and binaries to system folders. Also, make sure you have the folder where you cloned that repository in `.gitignore`, otherwise we'll try to sync it back to the sandbox contents, which is probably not what you want.

Also, be warned that we might delete the persistent volume the sandbox is backed by, based on our storage needs, so your compiled artifacts might get removed (it's not a probable scenario, but it might happen).

**Comment by frog-o** [comment]
@lbogdan would you mind updating this.  I think this is changed now that you have dev-containers(all thought in the cloud only).  I been play around with them you can set the container to root in devcontainer.json and get root access for the app in a container.  I would love to know if there any way to get root as a user t(this seem to be under development and have not found documention yet for it).
