### ISSUE TITLE
The Angular template is fourteen months out of date

### ISSUE THREAD

**Issue by jonrimmer** [CompuIves/codesandbox-client#1646]
# 🐛 bug report

## Description of the problem

Angular v5.2.0 was released 2018-01-10, but the Codesandbox Angular template is still using it as the dependency version in `package.json`. At the time of writing, the current version is v7.2.10, released 2019-03-20.

Compare this with the React template, which is at v16.8.3, released 2019-03-21.

Why is the React template kept up to date but the Angular one not?

## How has this issue affected you? What are you trying to accomplish?

I'm trying to create an Angular project on Codesandbox, I don't want a version over a year older than if I ran npm install on my local machine.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1550925883-24de5d4b
| Browser | Chrome
| Operating System | macOS

**Comment by lbogdan** [comment]
Hey @jonrimmer ,

The are two main reasons why we're lagging way behind the current Angular version:
- it takes **a lot** of effort for us (well, for @CompuIves , really 🙂 ) to update our in-browser bundler when the Angular major version changes - and sometimes that's true even for minor ones;
- since we released [CodeSandbox Containers](https://medium.com/@compuives/codesandbox-containers-out-of-beta-improvements-be79679df4cc) you can pretty much run anything inside a server sandbox, including the current Angular version, like I did here: https://codesandbox.io/s/github/lbogdan/cs-angular-starter .

That being said, we'll most probably add an Angular server template soon-ish!

If that answers your question, please help us keeping the open issue count in check by closing this! 🙂

**Comment by jonrimmer** [comment]
@lbogdan Thanks for the info. Here's hoping you do get this resolved soon, as I think, this issue aside, CS it is a great resource.
