### ISSUE TITLE
Stock vue template has a Babel error

### ISSUE THREAD

**Issue by gorbypark** [CompuIves/codesandbox-client#1659]
# 🐛 bug report

## Description of the problem
The stock vue template throws an error.  `[BABEL] /src/main.js: Invalid Option: corejs is not a valid top-level option.
        Maybe you meant to use 'targets'? (While processing: "base$0$0")`
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1553607023-33a33af1a
| Browser | Chrome 73
| Operating System | macOS

**Comment by AndreasCag** [comment]
Same issue. Today I published article about Vue.js form validations and found that all code examples not working.

I found fast fix: 
Replace this in package.json
```

    "@vue/cli-plugin-babel": "^3.4.0",
    "@vue/cli-plugin-eslint": "^3.4.0",
    "@vue/cli-service": "^3.4.0",
```

To this
```

    "@vue/cli-plugin-babel": "3.4.0",
    "@vue/cli-plugin-eslint": "3.4.0",
    "@vue/cli-service": "3.4.0",
```

**Comment by LeeChar** [comment]
> Same issue. Today I published article about Vue.js form validations and found that all code examples didn't work.
> 
> I found fast fix:
> Replace this in package.json
> 
> ```
> 
>     "@vue/cli-plugin-babel": "^3.4.0",
>     "@vue/cli-plugin-eslint": "^3.4.0",
>     "@vue/cli-service": "^3.4.0",
> ```
> To this
> 
> ```
> 
>     "@vue/cli-plugin-babel": "3.4.0",
>     "@vue/cli-plugin-eslint": "3.4.0",
>     "@vue/cli-service": "3.4.0",
> ```

It's starting to work properly.but why？

**Comment by lbogdan** [comment]
We're looking into this!

**Comment by CompuIves** [comment]
Hey! I found the issue, it's related to a recent new release of `@vue/cli-plugin-babel`. Some new configuration parameters were given to `@babel/preset-env` since `3.5.2`(https://github.com/vuejs/vue-cli/commit/156ef21c4238aa7ec3804db9d3c4817f8f69b209), but our `@babel/preset-env` installed in the sandbox was too old and threw a validation error. 

I installed a new version of `preset-env` in the sandbox as a temporary solution, that should be live in ~15min. A long-term solution would be to either add support for lockfiles or to use the `babel-preset-env` provided by `@vue/cli`.

**Comment by CompuIves** [comment]
The fix is live and the issue should be resolved! Sorry for the inconvenience, I'll make sure to run our CI check periodically and find a better solution for the env preset.

Thanks for the workaround @AndreasCag, that helped a lot with pinpointing the issue!

Let me know if it's fixed for you, then we can close the issue.

**Comment by lbogdan** [comment]
For future reference, the fix commit is https://github.com/CompuIves/codesandbox-client/commit/7cb89e2c8db3ed5669d21c56941bf4f3cd9b784b .

**Comment by lbogdan** [comment]
Closing this, as no feedback signals me this has been solved. Please reopen if that's not the case.
