### ISSUE TITLE
Styles lost when importing from GitHub

### ISSUE THREAD

**Issue by pshrmn** [CompuIves/codesandbox-client#171]
When I import from GitHub, the `index.html` file that is included in the sandbox contains the `<body>` contents from the source `index.html`, but not the `<head>` contents. This means that any `<style>` tags from the source will be removed.

Example:

https://github.com/pshrmn/curi/tree/master/examples/active-links
https://codesandbox.io/s/github/pshrmn/curi/tree/master/examples/active-links

Here is the same project created on CodeSandbox

https://codesandbox.io/s/J9x3n3k2

Per the above example, styles in the `index.html` of sandboxes created on CodeSandbox _will_ apply the correct styles. This is because the tags in the `<head>` get moved to the `<body>` when the sandbox is rendered. As a temporary workaround, I could do this as well, but it isn't an ideal solution.

I'm not sure how difficult it would be to store the styles on the HTML module object and then add it into the generated HTML (next to where the `externalResources` are inserted). I did a brief check, but didn't see where the HTML was getting parsed to create the module object.

**Comment by pandemm** [comment]
I think it is because of the html parser at the [Git-extractor project](https://github.com/CompuIves/codesandbox-git-extractor/blob/master/src/routes/github/create-sandbox/html-parser.ts). It extracts external css and js assets and the body content, but not style tags for example. 

@CompuIves  Am I correct that adding parsing for <style> tags would fix this? What other tags are there that we might want to parse from the <head>?

**Comment by CompuIves** [comment]
Ahh, interesting issue. You're both right @pshrmn and @pandemm, thanks for the digging!

I see two solutions:

The first possible solution is that we should have separate fields for script/style tags inserted in the head. This way we can reconstruct them back in the sandbox.

The second possible solution seems like we should just save the whole HTML file without the script/style tags, and let the sandbox reconstruct the head by parsing this.

I'm leaning towards the first solution, because I'm not very attracted to the idea that some sandboxes will have an `index.html` with a `head` and some won't. But I'd like to know your opinions as well, maybe I'm missing something or I'm misjudging.

**Comment by pshrmn** [comment]
Besides not losing the original styles, I think my biggest concern is just that someone who forks the imported project is able to easily edit the `<style>`s. I was imagining a system where the `index.html` has both `<head>` and `<body>` tags. However, I can understand why you wouldn't necessarily want a `<head>` in the `index.html` as it would lead to having to handle multiple use cases (whereas you can just dump everything into the `<body>` when the contents of `index.html` are assumed to just be the `<body>` nodes). I'm just not sure how you would be able to edit any styles otherwise.

```html
<!-- index.html -->
<head></head>
<body>
  <div id='root'></div>
</body>
```
With that, the user can easily toss a `<style>` tag in the `<head>`.

When generating an `index.html` file for a GitHub imported sandbox, anything besides `<style>` tags would be removed. I believe that `<script>`s could be stripped since they're already stored as external resources. I'm not sure exactly how CodeSandbox deals with `<link rel="stylesheet">`. Is there any way for those to be local, or are they external resources as well?

The `index.html` in the repo I linked above would end up something like this:
```diff
-<!DOCTYPE html>
-<html>
<head>
-  <title>Curi Active Links</title>
  <style type="text/css">
    a {
      color: blue;
    }
    a.active {
      color: red;
    }
  </style>
</head>
<body>
  <div id='root'></div>
-  <script src="https://unpkg.com/react@15.5.3/dist/react.min.js"></script>
-  <script src="https://unpkg.com/react-dom@15.5.3/dist/react-dom.min.js"></script>
-  <script src="./js/bundle.js"></script>
</body>
-</html>
```
(The above file isn't completely ideal since the linked repo sets the React files as external, leading to the script tags. As far as I know, they are unnecessary on CodeSandbox because React will be in the bundle.)

As far as some sandboxes having a `<head>` and others not, isn't that already partially true?
 https://codesandbox.io/s/J9x3n3k2 is a complete HTML file, and when it is rendered, the `<title>` and `<style>` tags are moved to the `<body>` of the HTML file rendered in the iframe.

Anyways, you are 100x more familiar than I am with how CodeSandbox works, so I'm not sure if what I am thinking is reasonable. If you have any questions, I am happy to chime in. I don't imagine this being too high a priority, just a nice to have feature, but I'm looking forward to any updates on this front. As always, thanks for building this awesome resource!

**Comment by SaraVieira** [comment]
Closed because demo does not exist anymore
