### ISSUE TITLE
Emmet.io support 

### ISSUE THREAD

**Issue by CompuIves** [CompuIves/codesandbox-client#20]
I've had some requests for emmet.io support. This should be possible with https://github.com/emmetio/codemirror.

**Comment by CompuIves** [comment]
It's better to use this: https://github.com/emmetio/codemirror-plugin

**Comment by vueu** [comment]
Hey, I've begun working on this and managed to get it functioning.

The only issue right now is that [these](https://github.com/CompuIves/codesandbox-client/blob/master/src/app/components/sandbox/CodeEditor/index.js#L240-L248) lines are interfering with defining `Tab` onto `emmetExpandAbbreviations`.

**Comment by CompuIves** [comment]
Awesome, this is great @vueu!

I think you could do something like this to make it work,

```js
// at the beginning
import emmetExpandAbbreviation from '@emmetio/codemirror-plugin/lib/commands/expand-abbreviation';

        Tab: cm => {
          // Indent, or place 2 spaces
          if (cm.somethingSelected()) {
            cm.indentSelection('add');
          } else {
            // Instead of the space addition
            return emmetExpandAbbreviation(cm);
          }
        },
```

This way we still have Tab indenting and emmet autocomplete.

Thanks for your work!

**Comment by vueu** [comment]
Sounds great, I'll get on it.

**Comment by CompuIves** [comment]
Also one thing: right now `emmet` autocompletes to `<div class="" />` while React only understands cases like `<div className="" />`. I did a quick lookup and it seems that we can change this by adding an emmet addon(?). I found it here: https://github.com/emmetio/expand-abbreviation/issues/2

**Comment by vueu** [comment]
I had totally spaced that fact, I'll include that `jsx` addon.

On another note, I'm back here with a roadblock. It seems the `lib` folder of `@emmetio/codemirror-plugin` is not included in the node module itself upon installing via yarn/npm, leaving `emmetExpandAbbreviation` inaccessible. What actually happens is it gives a built version of the package, ditching the source files.

In the repository for the codemirror-plugin, it tells to do `Tab: 'emmetExpandAbbreviation'`, so what I tried doing instead of `return emmetExpandAbbreviation(cm);'` was `return 'emmetExpandAbbreviation;`, however this did not work. I'm guessing since Tab is an anonymous function due to the changes made, the codemirror emmet plugin is actually getting the *function* rather than the *value the function returns*, because the function doesn't get called.

Any more ideas on what we can do?

**Comment by CompuIves** [comment]
Ah, I think I found it! From the emmet source I see that they register both commands to the CodeMirror instance, which means we can call them using `cm.execCommand` (https://codemirror.net/doc/manual.html#execCommand).

So (I hope) it should be possible to do something like this:

```js
        Tab: cm => {
          // Indent, or place 2 spaces
          if (cm.somethingSelected()) {
            cm.indentSelection('add');
          } else {
            // Instead of the space addition
            cm.execCommand('emmetExpandAbbreviation');
          }
        },
```

**Comment by vueu** [comment]
Great find! That has fixed the issue. Now, in the meantime I did a little work on the `class` vs. `className`. So I've got it working slightly, only in `jsx` files.

The link, [emmetio/expand-abbreviation#2](https://github.com/emmetio/expand-abbreviation/issues/2), you sent does lead me in the right direction, because it shows how to set default syntax and remap profiles.

I'll check in soon.

**Comment by CompuIves** [comment]
Great! Again, thanks a lot for this contribution. It's a heavily requested one 😄

**Comment by vueu** [comment]
Hey, checking in. Almost done here. Apparently there was a bug in the CodeMirror Emmet Plugin, and the Emmet expand-abbreviation config, linked above, was not being loaded into CodeMirror!

I created an issue and it was *very* quickly solved, so now I'm on the home stretch with this.
