### ISSUE TITLE
Can't seem to load pre-release versions of packages?

### ISSUE THREAD

**Issue by justinfagnani** [CompuIves/codesandbox-client#207]
I'm trying to create a sandbox that uses Polymer 3.0 preview, with the dependency `@polymer/polymer` at version `3.0.0-pre.1`. I don't see any errors from the dependency installation (maybe I don't know where to look?), but importing `@polymer/polymer` gives an error:

`Could not find dependency: '@polymer/polymer'`

I'm using the React template for lack of a better vanilla template.

Example sandbox is here: https://codesandbox.io/s/142kqkqqo4

**Comment by justinfagnani** [comment]
Same problem starting from the Vue template: https://codesandbox.io/s/m71717wol8

**Comment by petermbenjamin** [comment]
Same here.
Tried with `polymer` version `1.6.1` and `1.6.2` from a base Svelte template and received: `Could not find version: 1.6.1`

**Comment by CompuIves** [comment]
Good ones, I'll look into this this month.

**Comment by richardanaya** [comment]
Looking forward to this!

**Comment by JosefJezek** [comment]
@CompuIves any progress?

**Comment by CompuIves** [comment]
For the initial issue there was a problem with the polymer version. The `main` field was not set in pre-1 which caused CodeSandbox to think the dependency was not installed. A sandbox with a newer version is here: https://codesandbox.io/s/w6joz94m88.

I believe this is also the case for `polymer@1.6.1` on unpkg you can see that it cannot resolve https://unpkg.com/@polymer/polymer@1.6.1/. I'm not sure if I'm looking at the wrong package in this case.

Have you seen this for other cases as well @richardanaya and @JosefJezek? Maybe there is some other issue in CodeSandbox for other packages. Otherwise I'm inclined to close this issue.

**Comment by JosefJezek** [comment]
@CompuIves loading is ok, please close.

**Comment by justinfagnani** [comment]
@CompuIves some of our packages might not have main fields set. We're likely to unset it in Polymer 3.0.0 core in a upcoming release.

**Comment by CompuIves** [comment]
That's good to know @justinfagnani! We resolve the files the same way as node, so I think we should be fine. Our error messages are rather cryptic though, I'll put more effort to fix that!

I'll close this one now 😄
