### ISSUE TITLE
Lerna Support

### ISSUE THREAD

**Issue by artivilla** [CompuIves/codesandbox-client#248]
I think this is going a little out of scope for now, but for future reference, would love if this can support [lerna](https://github.com/lerna/lerna) since a lot of private larger repos are maintained this way.

Ref Repo: https://github.com/babel/babel
Error Message: The project should include a src folder. Network header tab shows `Status Code:422  (from ServiceWorker)` for req URL `https://codesandbox.io/api/v1/sandboxes/github/babel/babel`

**Comment by CompuIves** [comment]
Good one, I'll keep it in the issue list so we can take a look on it in a later stage. Thanks for the feature request!

**Comment by artivilla** [comment]
@CompuIves watched your Zeit talk which is where I heard about codesandbox. Love the enthusiasm!! Thanks for this work.

**Comment by CompuIves** [comment]
That's great! Love to hear that you liked it 😄 .

**Comment by lbogdan** [comment]
I'd say since the introduction of [server sandboxes](https://medium.com/@compuives/codesandbox-containers-out-of-beta-improvements-be79679df4cc), which (should) support `lerna` out-of-the-box, I don't think the effort to also implement it in client (browser) sandboxes makes sense anymore. Closing this for now, @artivilla feel free to reopen if you think otherwise.
