### ISSUE TITLE
Browser compatability

### ISSUE THREAD

**Issue by kblodget** [CompuIves/codesandbox-client#365]
I am starting to learn React and wanted to use codesandbox. I can not open the codesandbox in firefox version 31 or chrome version 36 using this url https://codesandbox.io/s/XDAE3x0W8. It hangs loading the sandbox. Unfortunately I have to use these browsers. Is there any way I can use this tool?

**Comment by chakrihacker** [comment]
Codesandbox uses service workers which are not supported by the version you are using, can you upgrade to v33 in ff or v40 in Chrome, so you can use it

**Comment by CompuIves** [comment]
Hey @kblodget, I did some checking with BrowserStack and found out that the root cause of incompatibility is that you don't have `Set` and `Map`.

I have a PR that could solve it here: https://github.com/CompuIves/codesandbox-client/pull/367. The one problem that's left is that we import `loader.js` in HTML (https://github.com/CompuIves/codesandbox-client/blob/polyfill-old-browsers/packages/app/src/app/index.html#L44), which requires Map and Set as well. Maybe we need to put the Map and Set polyfill conditionally in a separate script tag above `loader.js`

**Comment by kblodget** [comment]
Thank you for looking into this. I wish I could upgrade to FF33 but that is a requirement. Once the PR has been merged would I be able to use this tool. I am currently using it in FF 54 then download the changes and run the app on the older browser it  has been very helpful getting prototypes up and running quickly.

**Comment by lbogdan** [comment]
@kblodget Are you still struggling with those old browser versions?

**Comment by kblodget** [comment]
Thank you for all the help. I can close this issue
