### ISSUE TITLE
New projects w/o templates?

### ISSUE THREAD

**Issue by corysimmons** [CompuIves/codesandbox-client#366]
![image](https://user-images.githubusercontent.com/224636/33630873-d19e6aa4-d9d6-11e7-95a8-85067978426a.png)

Is there a way to just create a fresh project w/o any framework from the client?

**Comment by chakrihacker** [comment]
No

**Comment by CompuIves** [comment]
Not yet @corysimmons. I'd love to add a vanilla template though. The main question is what kind of template (like Babel config, Webpack config, maybe other bundler?) we'd use for vanilla.

I'd like to keep this issue open to discuss this.

**Comment by chakrihacker** [comment]
Hey, @compuives I heard about https://parceljs.org/, may be it suits to create vanilla template

**Comment by CompuIves** [comment]
Yah I saw it @chakrihacker, it looks awesome! I think it's too young to use yet, but it gave me an idea on how to handle vanilla templates.

I think we should just enable all features:

- TS Support
- CSS modules support (we detect it same way parcel does)
- Global CSS support
- Sass support
- Less support
- Stylus support
- Vue support
- Babel support
- Raw support

And enable them conditionally when you download the project in the end.

**Comment by corysimmons** [comment]
Possibly, but I wonder how slow live-reload would be for that.. Worth doing some benchmarks and possibly considering Parcel (this is the first I've heard of it, but its bundling speed looks like it could make your solution fast enough).

**Comment by corysimmons** [comment]
I'd also suggest doing a flow UI where people could start by selecting their preferred bundler, then checkbox what things they wanted to support and generate the bundler config that way.

Allow people to save these configs as their own templates and possibly share them in the community.

Seems cleaner/better.

**Comment by rhall91** [comment]
@CompuIves as a noob to things like webpack, sass, etc I like @corysimmons idea with the check boxes/toggles to pic the things you want to use.

**Comment by CompuIves** [comment]
I also like the points of @corysimmons very much. Having so many transpilers shouldn't have effect on performance, because the bundler of CodeSandbox lazy loads its transpilers based on usage.

Would be really cool to have an option for a 'Generate Template' where you can create your own config like @corysimmons and @rhall91 suggest. Though I like the approach of Parcel as well, requires no config. I can implement that easier, so I'm leaning to building that first, then add template support.

**Comment by corysimmons** [comment]
I don't see why Parcel + checkboxes can't co-exist. I haven't had time to play with Parcel, but if it lives up to the claims, then Parcel + checkboxes should be nice and easy*.

> * as "easy" as anything in programming ever actually is...

**Comment by rbiggs** [comment]
Hmmm... I like what you guys have done with Codesandbox, but I would never use it because it forces you to use the frameworks you've chosen: React, Preact, Vue, and Svelt. I'd never use them. I prefer to use lesser known libraries and frameworks, but you currently offer no way to create a project without your current templates. I'll be sticking with Codepen for now.

**Comment by CompuIves** [comment]
Some progress on this! I got a Parcel template running in CodeSandbox 😄 

![screen shot 2018-02-24 at 19 48 24](https://user-images.githubusercontent.com/587016/36633815-c9e9620a-199b-11e8-957d-72f37cfeae66.png)

**Comment by corysimmons** [comment]
Pretty sick. CodeSandbox keeps marching forward with actually implementing feature requests. :)

**Comment by sdaves** [comment]
Amazing work @CompuIves !

I tried out https://github.com/emaren84/ts-react-parcel a few months ago and was pleasantly surprised with parcel's abilities. 

@CompuIves Can you share the superpowers in package.json from yesterday's parcel example?

**Comment by CompuIves** [comment]
Thank you @sdaves! I'm planning to release the Parcel template next Wednesday, from then on I can also share some example projects.

**Comment by sdaves** [comment]
Awesome, can't wait!
