### ISSUE TITLE
Ember support

### ISSUE THREAD

**Issue by jrock2004** [CompuIves/codesandbox-client#442]
Any thoughts about getting Ember added in here?

**Comment by CompuIves** [comment]
Not yet set in stone, but I'm open to it!

I'm curious what Ember uses for bundling, does it use Webpack?

**Comment by kimroen** [comment]
I've been thinking about this ever since I first tried out CodeSandbox, and I came here today to look at what would be needed to support Ember. I'd love to help get something working if there's any interest at all 👍 

> I'm curious what Ember uses for bundling, does it use Webpack?

Ember uses [Broccoli](https://github.com/broccolijs/broccoli), which is pretty low-level. There's a lot of tooling built on top of it, all handled through [`ember-cli`](https://ember-cli.com/).

Creating an ember application goes like this:

```sh
npm install -g ember-cli
ember new my-app
```

Running a local dev server:

```sh
ember server
```

Making a production build:

```sh
ember build --environment=production
```

Running tests:

```sh
ember test
```

### Addons

The general idea is that you use ember-cli, and then extra libraries and build-time extras are managed through ember addons. For example to use `autoprefixer`, you install the `ember-cli-autoprefixer` addon:

```sh
ember install ember-cli-autoprefixer
```

Sass?

```sh
ember install ember-cli-sass
```

These types of addon normally hook into the build pipeline to transform the code at the right place using broccoli (`broccoli-autoprefixer`, for example), and also make some configuration available for the end user.

Moment.js?

```sh
ember install ember-moment
```

This will both add the library to the build and make some components and helpers for working with Moment available.

You wanna deploy to surge?

```sh
ember install ember-cli-surge
ember surge --login
ember surge
```

[Ember Observer](https://emberobserver.com/) is where one can go to find out about these.

Addons can do these things:

- Add steps to the build
- Add "generators" (`ember generate component my-component` is a built-in generator, for example)
- Add files and libraries to be included in the build
- Make components or other bits of code available
- Add generic commands to the `ember` command
- Probably other things I'm forgetting

#### Addons with CodeSandbox

Replicating `ember install` on CodeSandbox isn't as tricky as one might think, because what happens under the hood is that `npm install --save <name-of-addon>` is run (which there is already an interface for), and then the generator for the installed addon is run using `ember generate <name-of-addon>`. This is just node code running though, so there are surely some edgecases that could crop up here.

Ember addons have the keyword `ember-addon` in their `package.json`, so they can be detected in npm that way.

### Bower

Ember apps used to require `bower` to actually install the ember library, so there are bound to be some projects that people will try to import from github that won't work if that isn't supported.

### Alternatives

At the moment one can create ad-hoc alternatives to CodeSandbox by loading the right scripts into something like [Codepen](codepen.io], [jsbin](https://jsbin.com/), [jsfiddle](https://jsfiddle.net/) or similar, but all of these alternatives mean you have to use the globals-based version of Ember. None of them allow you to use the file structure, addons, and similar.

The closest you can get to the local setup is with [Ember Twiddle](https://ember-twiddle.com/), which is built specifically for Ember and the kind of scenarios that CodeSandbox helps with. CodeSandbox has some pretty clear advantages though, like the interface in general, the editor and the integrations with GitHub (Ember Twiddle loads and saves gists).

### First version

To get a working first version of this, we could ignore these things:

- Running addon generators
- Supporting Bower

And support these things:

- Generating a new Ember app
- Installing npm dependencies

**Comment by ddoria921** [comment]
I'm also interested in this. Any help on where to get started implementing this?

**Comment by jrock2004** [comment]
Is there documentation on how to implement a new framework? If so I would not be opposed to helping out

**Comment by CompuIves** [comment]
Hey @jrock2004, that would be really nice!

We don't have official documentation yet, however we have reference work and a small explanation.

We recently got a PR for a new custom template: https://github.com/CompuIves/codesandbox-client/pull/665. This PR does a really good job at implementing a new template. I also wrote an explanation here: https://github.com/CompuIves/codesandbox-client/issues/628#issuecomment-375693359.

Let me know if you have any other questions! I'm really interested in how good Ember support we can get 😄

**Comment by NullVoxPopuli** [comment]
I would also very much appreciate ember support :-)

**Comment by SaraVieira** [comment]
Ember has been added :D

**Comment by jrock2004** [comment]
@SaraVieira I just tried creating new ember project and it does not work. Should I open a new ticket?

**Comment by NullVoxPopuli** [comment]
I got this error:
![image](https://user-images.githubusercontent.com/199018/52959870-60c8da00-3365-11e9-801d-1b5a95cdca6c.png)

**Comment by NullVoxPopuli** [comment]
Also, I think for this to be completed, we need the terminal able to add files to the file list view. last I checked, that didn't work. :(

`ember g route route-name` should generate a few files and have them show up in the sidebar.

**Comment by NullVoxPopuli** [comment]
ok, so, one of my old ember sandboxes runs.
![image](https://user-images.githubusercontent.com/199018/52959959-9ff72b00-3365-11e9-8f3b-2dd2c1e73558.png)

I wonder if something is just broken with the template container then

**Comment by SaraVieira** [comment]
Hey!

Getting the terminal commands will be done when we may transfer it to server ones so you have ember CLI installed 
When containers get out of beta we may move this to them so you get all the commands 

If there is a problem with the template please create a new issue 

Sorry but it's better for us to keep track of issues :/

**Comment by NullVoxPopuli** [comment]
@SaraVieira I was just meaning that files generated with the CLI don't show up in the sidebar.
ember-cli already works :)

`yarn ember g component my-component` should show my-component in app/components, and app/templates/components

**Comment by SaraVieira** [comment]
Ohhh, that is weird, that is a bug :o

Do you mind making an issue with that specifically so we don't forget about it ?

**Comment by piotrpalek** [comment]
Is Ember actually on Codesandbox? I can't see it anywhere.

**Comment by NullVoxPopuli** [comment]
It's a server template, because it uses sandbox's containers to run instead of running purely in the browser.

I also think that the sandboxes should be organized by what they are, rather than their underlying sandbox technology, which the average user doesn't care about. 





![Screenshot_20190523-045221](https://user-images.githubusercontent.com/199018/58239164-925f9180-7d16-11e9-9df4-b485c617a442.png)

**Comment by piotrpalek** [comment]
Weird, I would think Angular also needs the container technology to work, but that doesn't seem to be the case.

**Comment by NullVoxPopuli** [comment]
Yeah, the code in the angular sandbox to hack the building into the browser is gnarly.

The ember sandbox is super simple, and just runs ember-cli
