### ISSUE TITLE
Dojo 2 Support

### ISSUE THREAD

**Issue by agubler** [CompuIves/codesandbox-client#447]
It would be awesome if we could get support for a Dojo 2 template.

Dojo 2 uses Webpack for bundling via the [dojo cli](https://github.com/dojo/cli-build-app). Please let us know if there is anything we can do to help with this!

**Comment by CompuIves** [comment]
Great! Thanks @agubler, we're certainly going to support Dojo 😄

**Comment by nicknisi** [comment]
I can take a look at implementing this.

**Comment by CompuIves** [comment]
That's great @nicknisi!

Since we run all the code in the browser we don't support node applications, but we will support them from ~April. We're working on supporting that. If implementing Dojo proves to be too hard to implement because of its reliance on node we could also postpone implementation until we have proper Node support.

**Comment by Nufflee** [comment]
This might also be the case with Dart support (#465) because it doesn't have JS API for invoking the compiler/transpiler as of yet.

**Comment by lbogdan** [comment]
Added in #665 .
