### ISSUE TITLE
GitHub import not working for some urls

### ISSUE THREAD

**Issue by vvo** [CompuIves/codesandbox-client#455]
Hi! I am trying to display a CRA app from one our of repositories with CodeSandbox without luck:
- https://codesandbox.io/s/github/algolia/instantsearch-templates/tree/master/React%20InstantSearch
- https://github.com/algolia/instantsearch-templates/tree/master/React%20InstantSearch

What are we doing wrong?

Thanks!

**Comment by CompuIves** [comment]
Ohh this is interesting. I think it has problems with parsing the space, I'll do some more investigating 🤓

**Comment by CompuIves** [comment]
Ah, okay, it seems like we don't propagate errors from our extractor properly anymore. These 404s are confusing. Let me fix that first.

**Comment by CompuIves** [comment]
Okay, we now show the proper errors again.

For this one:
https://codesandbox.io/s/github/algolia/instantsearch-templates/tree/master/InstantSearch.js

We're trying to get an entry point that doesn't exist.

For this one:
https://codesandbox.io/s/github/algolia/instantsearch-templates/tree/master/React%20InstantSearch

I think we have a bug because of the space.

**Comment by CompuIves** [comment]
Fixed!

**Comment by vvo** [comment]
Thanks for this!
