### ISSUE TITLE
How to include static json file for ajax REST call?

### ISSUE THREAD

**Issue by geoidesic** [CompuIves/codesandbox-client#457]
So generally web apps pull json data and then use that.
How can we emulate this on codesandbox without CORS?

I tried creating a static json file `list.json` in the app root and pointing the ajax call at `/list.json` but it returned HTML instead of json. Presumably that's because it's being delivered with the wrong headers.

Is there documentation that covers this? (I couldn't find documentation for this project)

UPDATE: I should clarify that I'm trying this using Vue. I think what is happening is that the Vue router is picking up the URL of the static file and processing it as if it was a route instead of serving the file – which I suppose makes sense because it's a browser app after all and not a web server. However hoping there is some way to spoof the back-end API within codesandbox otherwise one cannot show front-end code without a published backend (which is not always possible during the prototyping or development phase).

Here's what it returned instead of JSON:
```
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sandbox - CodeSandbox</title><link rel="manifest" href="/manifest.json"><link rel="shortcut icon" href="/favicon.ico"></head><body><div id="csb-loading-screen"></div><script type="text/javascript" src="/static/js/common-sandbox.98a9b853.js"></script><script type="text/javascript" src="/static/js/sandbox.054d1069.js"></script><script type="text/javascript" src="/static/js/sandbox-startup.030bf9d7.js"></script></body></html>
```

**Comment by CompuIves** [comment]
Hey! I'm sorry for the delayed response.

You can create a `list.json` file in the `static` directory, you should be able to access it then by going to `/list.json`. A vue example would be:

https://n74m8py83l.codesandbox.io/list.json
for
https://codesandbox.io/s/n74m8py83l

I hope this clarifies how it works, we should get some documentation on this 😄

**Comment by DanWahlin** [comment]
First off - thanks for creating such as great tool! Really appreciate all your hard work. Been telling a lot of people about it in training classes lately.

I know this issue is closed and you provided a viable workaround, but any chance of enabling the "assets" folder in Angular projects or providing a setting where any folder could be defined as the "static" files folder? While I can make the static folder work, it means having to update paths since for an actual Angular project on Github I'd have to reference src/statics/customers.json but when the project loads into CodeSandbox that would have to change to "/customers.json". Possible to do that of course - but it involves some manual manipulation which I'm trying to avoid so the Github projects can be run directly in CodeSandbox without any modification. Thanks!

**Comment by sourav-kumar** [comment]
Hey @CompuIves ,

I am trying to add a static json file, just to add a ajax call on that. I have added that json file inside the static folder, still I am unable to access that, please let me know if I am missing anything.

Here is the react sandbox example : https://codesandbox.io/s/jn75o98449

**Comment by CompuIves** [comment]
Hey! It should work if you put the file in `public`, that's how
create-react-app works internally. Here's a fixed sandbox:
https://codesandbox.io/s/kq352rvq5.

**Comment by sourav-kumar** [comment]
Thanks @CompuIves for your quick help!!
