### ISSUE TITLE
.jsx file extension support

### ISSUE THREAD

**Issue by CompuIves** [CompuIves/codesandbox-client#51]
This one should be easy to do, I found out that create-react-app does support the `jsx` extension. We should update the sandbox to handle these cases.

All the code for this resides in `src/sandbox/`, if you'd search for `js` you'll find where we check for the extension.

I *believe* all logic is in `src/sandbox/eval/js/index.js` and `src/sandbox/utils/resolve-module.js`.

**Comment by bengummer** [comment]
Hey @CompuIves I am keen to have a go at this issue in the next week or so. Been wanting to get to know the codebase so this seems like a good starting point.

P.S. I was initially confused by the issue title, thought it meant JSX support in the editor rather than filenames. Maybe "JSX file extension support"? No big deal either way :)

**Comment by CompuIves** [comment]
That's really great @bengummer! I updated the title, don't hesitate to message me if you have any questions 😄 .
