### ISSUE TITLE
Can't find the prettify button in the new UI

### ISSUE THREAD

**Issue by alekhka** [CompuIves/codesandbox-client#512]
The prettify button which used to be in the top right corner, now isn't there at all.

**Comment by CompuIves** [comment]
Thanks for letting us know! I added it back for nostalgia sake ;D. Fixed with #520. Should be live in 10 min.

We also have something called quick actions since recently (activate with CMD/Ctrl+Shift+P), this way you can prettify without touching your mouse. Another way is by setting keybinding for prettify in your preferences.

**Comment by alekhka** [comment]
Works perfectly! Didn't know of the quick actions, it is awesome!
