### ISSUE TITLE
bootstrap not found in ng cli project

### ISSUE THREAD

**Issue by pdngithub** [CompuIves/codesandbox-client#524]
In sandbox https://codesandbox.io/s/qzwn6lmzr6 I am trying to use bootstrap. I am doing so by adding it to the .angular-cli.json. The configuration is:

    {
      ...
          "styles": [
            "styles.css",
            "../node_modules/bootstrap/dist/css/bootstrap.min.css"
          ],
          "scripts": [
            "../node_modules/jquery/dist/jquery.min.js",
            "../node_modules/bootstrap/dist/js/bootstrap.min.js"
          ],
      ...

I am getting the error:

    ModuleNotFoundError
    Could not find module in path: 'bootstrap/dist/css/bootstrap.min.css'
    ▶ 22 stack frames were collapsed.
    This screen is visible only in development. It will not appear if the app crashes in production.
    Open your browser’s developer console to further inspect this error.
    This error overlay is powered by `react-error-overlay` used in `create-react-app`.

To me it looks as though either the program is not using angular cli to build, or if it is, it has bootstrap in a different location than where I have it on my local machine. Just a wild guess, however.

**Comment by CompuIves** [comment]
Hey @pdngithub, I found the origin of this error. I'll deploy a fix somewhere in the next 2 hours!

> To me it looks as though either the program is not using angular cli to build, or if it is, it has bootstrap in a different location than where I have it on my local machine.

That's right. CodeSandbox does everything in the browser, from bundling to evaluation. This means that we don't always have native integration with angular cli.

This problem occurred because we hadn't downloaded `bootstrap/dist/css/bootstrap.min.css` yet and couldn't find it. I now added the functionality that checks in `.angular-cli.json` if the file exists, if it doesn't we will download it before evaluation.
