### ISSUE TITLE
developing on localhost cannot create project

### ISSUE THREAD

**Issue by wuweiweiwu** [CompuIves/codesandbox-client#545]
0.0.0.0:8000/s/new 

displays this page instead of creating a new project

<img width="775" alt="screen shot 2018-02-12 at 10 20 01 pm" src="https://user-images.githubusercontent.com/35270620/36135968-f26462c8-1042-11e8-99d9-c4e9bb4761c5.png">

**Comment by chakrihacker** [comment]
Go to localhost:3000

**Comment by wuweiweiwu** [comment]
Thanks!

**Comment by dfsq** [comment]
http://localhost:3000/s/new doesn't seem to work. I see several Uncaugh Errors breaking /s/new page. I wonder how people run the project? Not sure if I'm missing something or this is the issue.

**Comment by CompuIves** [comment]
Hmm, I think this has to do with a build step that I forgot to add. Will be fixed with #577 and that one will be merged within the hour :).

**Comment by dfsq** [comment]
@CompuIves I see you now merged #577. However even with additional build step something is still breaking, as it's impossible to run the project by just running `yarn start` due to big amount of uncaught errors (like `Uncaught Error: _processChildContext is not available in React 16+.`, etc.). I assume it has something to do with Modal component using React 15 and the app 16. But not sure.
