### ISSUE TITLE
Cannot find module 'angular-bootstrap-md'.

### ISSUE THREAD

**Issue by mcristiano** [CompuIves/codesandbox-client#559]
I'm trying to use the mdbootstrap free enterprise component but I'm not getting it, I followed all the installation and configuration steps and it still will not, could anyone help me?

See my project: [https://codesandbox.io/s/kkpplyrqqo](https://codesandbox.io/s/kkpplyrqqo)
See in my app.module.ts erro in line **import { MDBBootstrapModule } from "angular-bootstrap-md";**

Instructions
[https://www.npmjs.com/package/angular-bootstrap-md](https://www.npmjs.com/package/angular-bootstrap-md)

_The component help says I need to declare the includes, I did, but I think the codesandbox does not accept :(_

`add following into tsconfig.json file located in root folder
"include": ["node_modules/angular-bootstrap-md/**/*.ts",  "src/**/*.ts"],
(note: there is also tsconfig.app.json file inside src folder, however if you want to use it, path should be different)

"include": [ "**/*.ts", "../node_modules/angular-bootstrap-md/index.ts" ]
`

**Comment by CompuIves** [comment]
This is a very good one. The editor shows it as an error, though it's working in the bundler. The reason is that we don't have the `node_modules` `.ts` files available for the Monaco editor.

What we need to do is this:

Our `fetch-dependency-typings` worker (https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/app/components/CodeEditor/Monaco/workers/fetch-dependency-typings.js) needs to download the `.ts` files if there's no `.d.ts` files.
