### ISSUE TITLE
Upgrade/Sync dependencies

### ISSUE THREAD

**Issue by MicheleBertoli** [CompuIves/codesandbox-client#589]
First of all, thank you very much - I love Codesandbox :)

Maybe I misunderstood how dependencies work on Codesandbox, but this is my problem:
I updated a dependency (`react-automata`) in https://codesandbox.io/s/n5vvn4jrpm and the app still uses the old version.
I can even remove the dependency from the UI clicking 'X', and the app works.
Also, when I download the source, the `package.json` and the `yarn.lock` show the old version.

Is this a bug? How do I upgrade/change a dependency on a box?

I'm happy to provide more information if needed.

**Comment by CompuIves** [comment]
Ah, I'm sorry for that. I think that this is a caching issue where the
state has gone into an inconsistent state. I thought it wouldn't be
possible,  but apparently it is.

Some questions. Did this happen after upgrading the dependency? Was the
dependency added with the 'latest' tag?

You can fix it by clearing your IndexedDB storage, I can take a closer look
at what causes this tomorrow first thing 😄.

**Comment by MicheleBertoli** [comment]
Thank you very much, @CompuIves.

When I first created the box, I used version `1.0.0-4` (which is the one I see when I download the package).
Then, I updated the dependency to `1.2.0` a few weeks ago (and it seemed to worke).
Yesterday, I tried to install `2.0.0-0` using the UI and, although the version in the sidebar and the `package.json` looks good, the version in use is the old one (I can tell it because a new feature is missing).

If I clear the `IndexedDB` then it complains when I remove the dependency - which is expected.
However, when I try to install it again, it still uses an older version (while it shows the right version number in the UI).

I hope this gives you more information.

**Comment by CompuIves** [comment]
Wow that's really strange indeed. Which new feature is missing? I'll do some testing now.

**Comment by MicheleBertoli** [comment]
So, I finally managed to get it working with 2.0 in the browser (I repeated the operation N times) - yay!
However, when I download the source it still uses `1.0.0.-4`.
This is not an issue for me as I wanted to use the latest version on the online sandbox, but you might want to investigate if there are problems syncing the package.
Thank you very much for your support!

**Comment by lennerd** [comment]
I seem to have the same or maybe a similar problem. I already cleared the IndexDB but still getting an old dependency (looks like a cached but invalid version stored for `next`).

https://codesandbox.io/s/intelligent-aryabhata-rfl0m?file=/index.tsx

When clicking the buttons you should read "Loading …" underneath. But this is a bug fixed in the last version, working both when trying it locally or downloading the CodeSandbox via zip file. In the fixed version you only see a "Loading …" fallback text when loading some data for the first time. After that when clicking the button profile information should stay the same until new data was fetched.

Anything I can do to fix this?

**Comment by lennerd** [comment]
I should add that when using `react-pending-resource: "1.0.0-beta.3"` as a dependency its also the using the right version of the package. The problem only occurs with `next`.
