### ISSUE TITLE
Angular styles support information

### ISSUE THREAD

**Issue by vvo** [CompuIves/codesandbox-client#594]
Hey hi, using this project: https://github.com/algolia/instantsearch-templates/tree/master/src/Angular%20InstantSearch which is an angular-cli regular project, I cannot import css files from node_modules.

The project is working locally though, but on CodeSandbox it fails for some reason I cannot understand.

Here's the code I am trying to use:

```scss
@import '~angular-instantsearch/bundles/instantsearch.min.css';
@import '~angular-instantsearch/bundles/instantsearch-theme-algolia.min.css';
```

Which means "load node_modules/angular-instantsearch/...", per https://github.com/webpack-contrib/sass-loader#imports.

But on CodeSandbox at https://codesandbox.io/s/github/algolia/instantsearch-templates/tree/master/src/Angular%20InstantSearch, this gives:

![image](https://user-images.githubusercontent.com/123822/36687272-625a65e6-1b29-11e8-8cef-764fcbdfc409.png)

```txt
CompileError
Error: Could not find /src/node_modules/~angular-instantsearch/bundles/instantsearch.min.css
        on line 2 of /stdin
>> @import '~angular-instantsearch/bundles/instantsearch.min.css';
   --------^
```

**Comment by CompuIves** [comment]
Heh, interesting. It seems like it doesn't understand the `~`. I'll check it out now.

**Comment by CompuIves** [comment]
Will deploy a fix in a couple minutes! By the way, I noticed that the sandbox is using `lodash-es` (I'm not sure if via dependency or directly). The sandbox can load a bit slow, the reason is that it needs to transpile all used files in `lodash-es` first, to convert it to commonjs. Normally we don't transpile `node_modules` unless we detect `import`/`export` statements in the code. Just a small headsup 😄.

**Comment by vvo** [comment]
Interesting, thanks for being so responsive too!
