### ISSUE TITLE
Deploy failed with React

### ISSUE THREAD

**Issue by MAPESO** [CompuIves/codesandbox-client#680]
Try to deploy 2 times but keep failing :(

<img width="1280" alt="screen shot 2018-03-31 at 5 50 26 pm" src="https://user-images.githubusercontent.com/16585386/38168554-b5047f50-350c-11e8-9885-24488a6f98da.png">

**Comment by FDiskas** [comment]
source code needed :) :crown:

**Comment by mdugue** [comment]
Can confirm. This happens when you try to deploy the default React-Template to `now`. For example this: https://codesandbox.io/s/1yp7l1mkxj one. Not sure what the reason is, but the now logs show repeated running of the `npm run now-start` script

<img width="820" alt="image" src="https://user-images.githubusercontent.com/894149/38614871-01729c0c-3d8f-11e8-84f2-92f140f5b026.png">

**Comment by mdugue** [comment]
Actually I just realized that this is due to the `homepage` setting in `package.json` (as the log indicates). Removing this solved the problem for me.

**Comment by mdugue** [comment]
@CompuIves what would be the preferred solution, simply removing the `homepage` entry from `package.json`-template or are you planning to adjust the deployment scripts? 

For the first solution I could try to provide you a PR 😄.

**Comment by CompuIves** [comment]
Ah that makes a lot of sense. Thanks for the clear debugging @mdugue! Seems like it's best to just remove the `homepage` field from the `new` sandbox. I think I'm only able to fix this one since I only have permissions to change the `new` sandbox. I'll add you as collaborator for debugging this issue!

**Comment by CompuIves** [comment]
Hmm, to make it backwards compatible it would still be smart to remove the homepage field if template is `create-react-app`. Would you be interested in adding this logic @mdugue? We do package.json logic here:

https://github.com/CompuIves/codesandbox-client/blob/master/packages/app/src/app/store/modules/deployment/actions.js#L30

**Comment by mdugue** [comment]
Sure!

Von meinem iPhone gesendet

**Comment by mdugue** [comment]
@CompuIves not sure if I can label this issue. Do I need to do sth special or could you assign this "someone is working on it"?

**Comment by CompuIves** [comment]
I'll do it now!

**Comment by mdugue** [comment]
Thanks.
Also, do you have instructions somewhere pointing to how to setup the github-auth-workflow for local development. As I understand this is required to be able to trigger deployments.

**Comment by mdugue** [comment]
If not – nevermind – I'll figure it out…

**Comment by SaraVieira** [comment]
Closed by https://github.com/CompuIves/codesandbox-client/pull/725

Thank you man!
