### ISSUE TITLE
Allow changing sandbox name by clicking on the title

### ISSUE THREAD

**Issue by divyanshu013** [CompuIves/codesandbox-client#721]
Currently, the title of sandbox ('multilist' in the attached screenshot) takes me to the homepage. I was thinking probably it would be good for it to instead open the project info view to edit the sandbox title or maybe allow editing it inline? I usually end up clicking the title later to realize that I got redirected to the homepage 😅.

Let me know if this makes sense to you CompuIves, will be happy to contribute :)

![image](https://user-images.githubusercontent.com/6682655/38608579-635fa4dc-3d99-11e8-9ef8-9f44f42505b1.png)

**Comment by CompuIves** [comment]
This is a good UX improvement, someone else mentioned this issue last week as well and I 'fixed' it by changing the title field to `Sandbox Editor`, regardless of the sandbox title. Seems like you haven't received that update yet for some reason 🤔.

I think it makes the most sense to show 'Sandbox Editor' there, to keep consistency with Profile page (/u/:username) where we show 'Profile Page' instead of username. But I'm open to feedback/suggestions on this! Maybe it does make sense to show sandbox title from a user perspective.

**Comment by CompuIves** [comment]
Ugh, that's probably the service worker -again. I agree with you, it's best
if we show the title. Would you be interested in opening a PR where
clicking on the title allows you to edit it (or any alternative way to
edit)?

**Comment by divyanshu013** [comment]
Sure, I think I'll be able to get to it this weekend, will keep you posted here 😄

Any heads up on where to look into for this?

**Comment by lbogdan** [comment]
@divyanshu013 As dev is actually using the production API, you can copy the JWT auth token from `https://codesandbox.io`'s local storage to `http://localhost:3000` (its key is `jwt`). **Be careful with how you handle the token**, as anyone that has access to it can login as you.

![](https://bogdanl.tinytake.com/media/757524?filename=1525108254414_30-04-2018-08-10-50.png&sub_type=thumbnail_preview&type=attachment&width=550&height=81)

**Comment by divyanshu013** [comment]
Thanks @lbogdan :)

**Comment by lbogdan** [comment]
Closing this as implemented.
