### ISSUE TITLE
React Error Boundaries 

### ISSUE THREAD

**Issue by TENsaga** [CompuIves/codesandbox-client#741]
Are Error Boundaries not working with code sandbox? Or did I not write this correctly 😄 

example: https://codesandbox.io/s/qxxqv1qkv4

Was staring at this for awhile, I found another sandbox with the same outcome: https://codesandbox.io/s/3yxmxw9lj5

This seems like it works, but it's a bit of a workaround: https://codesandbox.io/s/64n5k8y87k

Thanks for the amazing tool.

**Comment by alexvcasillas** [comment]
I'm able to see the problem here: [https://codesandbox.io/s/m45q3lz0pp](https://codesandbox.io/s/m45q3lz0pp)

The sandbox I gave you there is an exact reproduction of [this pen](https://codepen.io/gaearon/pen/wqvxGa?editors=0010) by Dan Abramov where he shows how to handle errors in React 16 with the componentDidCatch.

Somehow the sandbox is not being able to reproduce the behaviour and we should investigate further into this.

The [last example](https://codesandbox.io/s/64n5k8y87k) you gave us it's a heavy work around :)

In fact ...

```
catchFunctionErrors = fn => async (...args) => {
    try {
      await fn(...args);
    } catch (error) {
      this.setState({
        hasError: true,
        errorMessage: error
      });
    }
  };
```

By doing this kind of stuff (imperative coding) you're blocking the render method and you're wrapping each of the components with this boundaries component 🤔 I can't agree with this kind of behaviour in that React component.

```
wrapRecursive = children => {
    return React.Children.map(children, child => {
      if (!React.isValidElement(child)) {
        return child;
      }
      if (child.props.children) {
        child = React.cloneElement(child, {
          children: this.wrapRecursive(child.props.children)
        });
      }
      const wrappedProps = Object.keys(child.props).reduce((props, key) => {
        return typeof child.props[key] === 'function'
          ? Object.assign(props, {
              [key]: this.catchFunctionErrors(child.props[key])
            })
          : props;
      }, {});
      return React.cloneElement(child, wrappedProps);
    });
  };
```

In the above example is wrapping all of the descendants of this Error Boundary component and I don't get the point of doing this since the component with the lifecycle `componentDidCatch()` will handle this by itself within it's descendants but not for his parents of sibilings :)

**Comment by CompuIves** [comment]
Hmm, I'm curious if `create-react-app` locally is showing the same behaviour as CodeSandbox. We catch errors and show them in the overlay the same way CRA does. It seems like we catch the error boundary error as well, before React does. Hmmm 🤔

**Comment by alexvcasillas** [comment]
Yes, that's what I'm thinking about, it has to be related to `create-react-app` because in the Dan's example, it's just the UMD version of React + ReactDOM so... I bet it has to be related to that... I'm giving a try to create-react-app right now and I'll tell you whenever I've tested it @CompuIves : )

**Comment by CompuIves** [comment]
Ah yes, so I think it comes down to that we need to fix the exit button of the error overlay? I think I broke it in a recent release.

**Comment by alexvcasillas** [comment]
Yes, I also think that could solve the problem :)
If you know where it is maybe it could be simple, but if you point me at the right direction maybe I could fix it for you if your so busy :)

**Comment by lbogdan** [comment]
@TENsaga , @alexvcasillas 
Take a look at http://pr768.cs.lbogdan.tk/s/qxxqv1qkv4 , it should work as expected. You can close the error overlay by clicking on the **x** close button or by pressing ESC. I also made it translucent, so you can peek *behind* it.

@CompuIves Btw, we forked from `react-error-overlay` 1.0.10 and not it's already at 4.0.0. :smile:

**Comment by TENsaga** [comment]
@lbogdan right on, looks great! Thanks for digging into this.

**Comment by drcmda** [comment]
do error boundaries really work in csb? the overlay should not be there if they did and all react examples i've tried crash. i see that i can click them away but that's beside the point.

**Comment by apresmoi** [comment]
I completely agree with @drcmda. The error boundaries in React apparently work... but the overlay is really counterintuitive. The opacity and the close mark aren't visible at all....

What do you think about some type of configuration on the sidebar to be able to opt-out those overlays ?
