### ISSUE TITLE
Importing css using an import statement sometimes produces different results to linking the same css in index.html using a link tag

### ISSUE THREAD

**Issue by pbastowski** [CompuIves/codesandbox-client#743]
It seems to me that css imports using the `import` statement in `main.js` are not working properly in CodeSandbox. However, when the same css file is linked in index.html using a `LINK` tag then everything works as expected. 

See this https://codesandbox.io/s/z1610no8p

Please notice the alignment of the checkbox and the input that says "What needs to be done".  They align vertically in the centre, see picture below.

![image](https://user-images.githubusercontent.com/5649024/38895512-8616f93e-4290-11e8-8662-64d844ae9747.png)

Next, comment out the link tag in index.html, which imports the `vuetify.min.css` file and now notice that the checkbox and the input no longer align vertically in the center. See the second picture, below.

![image](https://user-images.githubusercontent.com/5649024/38895570-b12ba214-4290-11e8-8284-7380b6c50b20.png)

I have had this issue with some other css files also, and had to resort to linking the css in index.html in addition to leaving the import in my js files. 

Also see: https://codesandbox.io/s/xr1l3rq79q

Here, if you comment out the link tag for font-awesome, the fonts don't load at all, even though I am importing the same css in main.js.

Please note that after changing index.html you have to reload the browser preview to see the changes.

**Comment by lbogdan** [comment]
Hey @pbastowski ,

That's pretty much an issue with how CSS rules apply depending on the styles loading and evaluation order. In your case the material icons font has to be loaded before Vuetify styles (otherwise font's `.material-icons` class will override Vuetify's `.icon` class, changing `display` from `inline-flex` to `inline-block` and messing the checkbox alignment). When one css is loaded from `index.html` and the other is loaded from `main.js` (using `import 'path/to/styles.css';`) the order in which they get loaded and evaluated cannot be controlled (actually it seems like Vuetify always goes before the font).

A workaround would be to also load the font from a css file using `@import url(https://fonts.googleapis.com/css?family=...)` and importing the css file from `main.js` **before** importing Vuetify styes. I made an example here https://codesandbox.io/s/qvxxz6q219 .

**Comment by pbastowski** [comment]
Hi @lbogdan 

Thanks for the explanation. 

There must be a difference in the load order of css chinks between CodeSandbox and the same app bundled and served by vue-cli 3. With vue-cli I don't get this problem. Only in CodeSandbox.

**Comment by lbogdan** [comment]
We currently only support the legacy `vue-cli` 2.x template. We'll add `@vue/cli` 3.0 support as soon as it's released. I opened a reminder issue here #776, you can follow it if you want to be notified.
I'll close this now, please re-open if you have any more related issues.

**Comment by pbastowski** [comment]
@lbogdan 
Thanks
