### ISSUE TITLE
React scripts is not found on cdn.jsdelivr.net

### ISSUE THREAD

**Issue by borm** [CompuIves/codesandbox-client#785]
Steps to reproduce

1. go to [codesandbox](https://codesandbox.io/)
2. choose create new react box

![image](https://user-images.githubusercontent.com/4027842/39527042-1ff807f2-4e29-11e8-8d3e-ddba2b2b9231.png)

**Comment by lbogdan** [comment]
Hey @borm , thank you for the report!

This error is expected (it's a feature, not a bug :slightly_smiling_face: ), and it's caused by [monaco-editor](https://github.com/Microsoft/monaco-editor), the default editor used by CodeSandbox, as it tries to load TypeScript definition files (notice the `.d.ts` extension, also the definitions are, by default, found in a separate typings package named `@types/package-name`) for the packages used by the sandbox, and the `react-scripts` package has no such typings.

If you try switching to the other editor available in CS, CodeMirror, you'll see the error go away, because it doesn't have this feature.

**Comment by lbogdan** [comment]
You can also turn off the automatic download of typings using the "Automatic Type Acquisition" setting in your preferences.

**Comment by borm** [comment]
Hey, okay, can you set `CodeMirror` as default editor until the error with monaco is eliminated?

And if you can, please show me where i can change default editor

**Comment by CompuIves** [comment]
Note that that error message is only to notify the user, it doesn't change
behavior since it's caught. I'm not sure if it makes sense to change the
editor for a console.error statement.

You can change the editor in preferences, you can find preferences in the
header under your user menu.

**Comment by borm** [comment]
![image](https://user-images.githubusercontent.com/4027842/39921367-4793db32-5523-11e8-8058-8af2222b679a.png)

What wrong? https://codesandbox.io/s/4xq2qpzw79
