### ISSUE TITLE
Make react and react-dom mandatory dependencies (or show error message when these deps are missing)

### ISSUE THREAD

**Issue by Arthelon** [CompuIves/codesandbox-client#85]
I noticed that if you remove the `react` and `react-dom` deps no error message appears but the output remains frozen.

### Solution:
Show error message when this happens or make these 2 packages mandatory dependencies.

**Comment by CompuIves** [comment]
Oh that's really strange! I think we should solve the underlying issue of the output staying frozen. I don't want to make `react` and `react-dom` required, because we do allow other frameworks to be used. We're just not focussing on improving other frameworks yet.

I was not able to reproduce the issue, I'm probably doing different steps.

Could you give a step by step on how to reproduce this?

**Comment by Arthelon** [comment]
Sure, here are the steps:
- Remove `react` from Dependencies list
- Remove `react-dom` from Dependencies list 
- Click "Save" button in Editor view

Running on Chrome 59.0.3071.115 (64 bit)
