### ISSUE TITLE
Ability to change template

### ISSUE THREAD

**Issue by fzaninotto** [CompuIves/codesandbox-client#864]
Currently, whether I create a sandbox from the ui, from a GitHub repo, or from the CLI, a template is chosen for me (e.g. create-react-app, parcel). But the detection is sometimes wrong (e.g. creating a sandbox from https://github.com/marmelab/react-admin/tree/master/examples/simple detects it as "create-react-app", which is wrong), or we may want to change our minds. 

So the ability to switch to another template would really be great.

**Comment by bbgrabbag** [comment]
This is the one feature preventing our organization from using CodeSandbox as our primary teaching assessment tool. Students submit their assignments (in the form of a Github URL) via our LMS. Unfortunately, since the auto template is not always accurate (we do more than just create-react-app),  it makes it difficult for us to test their code and provide feedback. 

Being able to switch templates within a project would instantly resolve our bottleneck. Thank you!

**Comment by jthegedus** [comment]
I have experienced this issue too, even after adding a `sandbox.config.json` with
```json
{
  "template": "parcel"
}
```                  

The "Project Info" tab still shows the auto-detected template, not the explicitly defined one.

**Comment by CompuIves** [comment]
This one is coming in today! You can set your template in `sandbox.config.json` and if it changes we update all settings.

**Comment by wmhilton** [comment]
This is awesome @CompuIves ! I successfully converted my React template project to a Vanilla template project and started using the `alias` package.json field #467 and now have a monorepo-style project!

**Comment by CompuIves** [comment]
Coool! I'll close this one now 😄

**Comment by jyjin** [comment]
@wmhilton Hi~ , I have the same problem with alias, Could you show me the demo which uses alias in codeSandBox?

**Comment by jyjin** [comment]
> This is awesome @CompuIves ! I successfully converted my React template project to a Vanilla template project and started using the `alias` package.json field #467 and now have a monorepo-style project!

Hi~ , I have the same problem with alias, Could you show me the demo which uses alias in codeSandBox?
