### ISSUE TITLE
ModuleNotFoundError for devextreme module

### ISSUE THREAD

**Issue by lukyanovas** [CompuIves/codesandbox-client#888]
# ❔ Question

Hi! 
When I try to import [devextreme-vue](https://github.com/DevExpress/devextreme-vue), I get the ModuleNotFoundError. What do you think? Is it a bug? 
### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | Chrome 66.0.3359.181 
| Operating System | Win 8.1

**Comment by CompuIves** [comment]
Ahh, I took a look and it turns out that `devextreme` is a huge package. I improved our packager to detect this, so in future versions the sandbox should load faster. I also fixed the issue you mentioned, the sandbox will now load, and if you update `devextreme` in the future it *should* also load fast.

**Comment by groshenkovamarina** [comment]
Hi! 
I found the same error when importing another devextreme module. Could you check if it's related to the previous problem? Here is a [link](https://codesandbox.io/s/k2jnyp5707/) to the sandbox.
