### ISSUE TITLE
Unexpected Token, the error does not help.

### ISSUE THREAD

**Issue by trusktr** [CompuIves/codesandbox-client#963]
https://codesandbox.io/s/vy9j9rq0n3

This happens to me in multiple sandboxes with different templates. For example, also this one:

https://codesandbox.io/s/5k59jnor8x

The errors are completely useless, I've no idea what's wrong. I mean, I see it complains about `{`, but the error itself provides no clue other than that. The stack trace is meaningless.

**Comment by trusktr** [comment]
How do I get it to not transpile anything except JSX? I just want to run in Chrome, I don't need it transpiling anything except JSX syntax. There's so much behind the scenes, it's impossible to tell why it doesn't work.

**Comment by trusktr** [comment]
This is very frustrating. Another one: https://codesandbox.io/s/llnxq5xy1m

I've just wasted half a day, and gotten nothing to work.

The "vanilla" template is not so.... vanilla.

**Comment by trusktr** [comment]
I switched over to glitch. It's much easier. It shows all errors in the console directly from Webpack, etc.

**Comment by trusktr** [comment]
Glitch screenshot, shows full Webpack output, etc. Much helpful:

<img width="1792" alt="screen shot 2018-07-14 at 5 50 10 pm" src="https://user-images.githubusercontent.com/297678/42729469-66d260d4-878e-11e8-8c07-8bbceb7b3ec8.png">

Glitch isn't tied to specific build systems or libs at all, it's just a node app, and it can serve anything. How it does that is completely up to the user. It doesn't default to something like Parcel. If Codesandbox did this, it could still offer templates, just that the full template would be visible and editable.

**Comment by CompuIves** [comment]
Oii, yeah those error messages are really bad. I'm sorry that you had such a bad experience with these vague error messages.

We should improve syntax errors thrown by babel in general, I will look into improving this.

Regarding your point in tying to build systems, CodeSandbox runs completely in the browser. It doesn't run Webpack itself, it runs a bundler built for the browser that has compatibility with Webpack loaders. This gives you things like offline support, faster reloading and instant spinups of projects, but it comes with the cost that we cannot 'just' run Webpack and show all the output.

That's a huge disadvantage for some more custom projects, so that's why we're also currently working on a server executed version of templates. And we will release that as a beta on August 1st. So hopefully that will remedy your frustrations then.

Sorry for the bad experience, I'll set up proper syntax error windows as a short term fix and as a long term fix the server side evaluation for certain templates.

**Comment by thenakedthunder** [comment]
It's been two years and the error messages are still useless in CodeSandBox. Like when you get like 5 and you know that there are ones that can be ignored because they are in fact not errors, and trying to figure out which one is a REAL error. Of course no error message out of the five means ANYTHING.
